### ISSUE TITLE
[Bug] Instant crash when viewing recipes made with the Infusion Ritual using EMI

### ISSUE THREAD

**Issue by relt-1** [quiqueck/BetterEnd#128]
### What happened?

When using EMI, viewing recipes that are made with the Infusion Ritual crash the game instantly
![obraz](https://user-images.githubusercontent.com/60782515/206990884-bea3d260-3002-4ff3-9b77-21b5de6c9d60.png)
1. Lookup gold ingot in the search bar
2. Right click it to get the recipes
3. Click the Infusion Ritual tab
4. The game will freeze for a couple seconds and then close

### BetterEnd

2.1.2

### BCLib

2.1.5

### Fabric API

0.69.0

### Fabric Loader

0.14.11

### Minecraft

1.19.2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-12-12 08:44:20
Description: Rendering screen

java.lang.NoClassDefFoundError: dev/emi/emi/EmiConfig
	at org.betterx.betterend.integration.emi.TransparentSlotWidget.method_25394(TransparentSlotWidget.java:64)
	at dev.emi.emi.screen.RecipeScreen.method_25394(RecipeScreen.java:212)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: dev.emi.emi.EmiConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.betterx.betterend.integration.emi.TransparentSlotWidget.method_25394(TransparentSlotWidget.java:64)
	at dev.emi.emi.screen.RecipeScreen.method_25394(RecipeScreen.java:212)

-- Screen render details --
Details:
	Screen name: dev.emi.emi.screen.RecipeScreen
	Mouse location: Scaled: (495, 26). Absolute: (991.000000, 53.000000)
	Screen size: Scaled: (960, 499). Absolute: (1920, 997). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['relt_'/183, l='ClientLevel', x=219.72, y=-17.00, z=865.70]]
	Chunk stats: 1024, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (172,71,843), Section: (at 12,7,11 in 10,4,52; chunk contains blocks 160,-64,832 to 175,319,847), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Level time: 65272 game time, 65272 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Fabrication

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1373226496 bytes (1309 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Devguru Twomon WDDM Display Driver
	Graphics card #0 vendor: Devguru
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=2.0.52.0
	Graphics card #1 name: Radeon RX 5500 XT
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x7340
	Graphics card #1 versionInfo: DriverVersion=30.0.15021.11005
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Virtual memory max (MB): 32617.70
	Virtual memory used (MB): 21974.68
	Swap memory total (MB): 16308.85
	Swap memory used (MB): 268.48
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		bclib: BCLib 2.1.5
		betterend: Better End 2.1.2
		betternether: Better Nether 7.1.2
		blastingsand: Smelting Sand In Blast Furnace 1.19.2-11
		chisel: Chisel Refabricated 1.4.5
		collective-fabric: Collective (Fabric) 5.22
			fiber: fiber 0.23.0-2
		computercraft: CC: Restitched 1.101.2
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		continuity: Continuity 2.0.1+1.19
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			flywheel: Flywheel 0.6.8-1
			forgeconfigapiport: Forge Config API Port 4.2.6
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			noindium: No Indium? 1.1.0+1.19
			porting_lib: Porting Lib 2.1.623+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.623+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.623+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.623+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.623+1.19.2
				porting_lib_models: Porting Lib Models 2.1.623+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.623+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.623+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.623+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.623+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.623+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.623+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.623+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.623+1.19.2
						porting_lib_common: Porting Lib Common 2.1.623+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		emi: EMI 0.5.0+1.19.2
		enderchests: EnderChests 1.1.0
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.69.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.30+b0bc9a6790
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabrication: Fabrication 3.1.3+1.19
			lib39-deferral: Lib39 (Deferral) 1.1.1
		fabricloader: Fabric Loader 0.14.11
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		gravestones: Gravestones v1.13
			cloth-config: Cloth Config v6 7.0.72
				cloth-basic-math: cloth-basic-math 0.6.1
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.4.5
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		more_slabs_stairs_and_walls: More Slabs, Stairs, and Walls 2.1.0
		mousetweaks: Mouse Tweaks 2.22
		placeableblazerods-fabric: Placeable Blaze Rods (Fabric) 2.4
		presencefootsteps: Presence Footsteps 1.6.3
			kirin: Kirin UI 1.11.1
		shetiphiancore: ShetiPhianCore 1.3.3
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.16
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		wilderwild: Wilder Wild 1.1.5-Fabric+1.19.2
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			frozenlib: FrozenLib 1.1.6-Fabric+1.19.2
			mm: Manningham Mills 2.3
			nbtcrafting: NBT Crafting 2.2.3+mc1.19
		wiredredstone: Wired Redstone 0.4.12+1.19.2
			graphlib: Graph Lib 0.3.4+1.19
			libmultipart_deps_container: LibMultiPart (Dependency Container) 0.8.0-pre.1.6+kneelawk
				libblockattributes_core: LibBlockAttributes (Core) 0.11.0-pre.1.3+kneelawk
				libmultipart: LibMultiPart 0.8.0-pre.1.6+kneelawk
				libnetworkstack: Lib Network Stack 0.7.1-pre.0.3+kneelawk
			lmp-compat: LMP Compat 0.2.1+1.19
			team_reborn_energy: Energy 2.2.0
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Radeon RX 5500 XT GL version 3.2.14800 Core Profile Forward-Compatible Context 22.5.1 30.0.15021.11005, ATI Technologies Inc.
	Window size: 1920x997
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['relt_'/183, l='ServerLevel[epic]', x=219.72, y=-17.00, z=865.70]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```

### Other Mods

```shell
emi-0.5.0+1.19.2
iris-mc1.19.2-1.4.5
sodium-fabric-mc1.19.2-0.4.4+build.18
```

**Comment by ghost** [comment]
Same Here ! [Logs Here](https://mclogs.minestrator.com/m3AHusQ)

**Comment by quiqueck** [comment]
Yeah, the current one does not work with the latest EMI updates. Will fix soon...

**Comment by MageInBlack** [comment]
> Yeah, the current one does not work with the latest EMI updates. Will fix soon...
Still seems to be an issue. Both Fabric and Quilt. But now instead of crashing it shows this

log:
https://mclo.gs/9mk8J88
![Screenshot_20230129_050528](https://user-images.githubusercontent.com/61745363/215300545-ca9814c8-6626-4e7a-80ca-eac3d79f07a1.png)

**Comment by Chikage0o0** [comment]
I have suggested edits. @quiqueck 
https://github.com/quiqueck/BetterEnd/commit/533b269f3c850c68f6a5a107ef3ec5e904439c72

**Comment by Niketats** [comment]
> > Yeah, the current one does not work with the latest EMI updates. Will fix soon...
> > Still seems to be an issue. Both Fabric and Quilt. But now instead of crashing it shows this
> 
> log: https://mclo.gs/9mk8J88 ![Screenshot_20230129_050528](https://user-images.githubusercontent.com/61745363/215300545-ca9814c8-6626-4e7a-80ca-eac3d79f07a1.png)

same

**Comment by MageInBlack** [comment]
Seems to be fixed in the latest update. At least for me
