### ISSUE TITLE
[Bug] Client crashing on connect.

### ISSUE THREAD

**Issue by MylesGit** [quiqueck/BetterEnd#132]
### What happened?

Using Better End 3.1.1 on 1.19.3. This is for both server and clients. I am able to join the server just fine but my girlfriend with the exact same files cannot join without her client crashing. I am on Linux and she is on Windows. I have copied the files directly over from my PC to hers and the crash persists. Stumped on what this is about. 

Additional Info:
Client is Prism Launcher 6.1
Minecraft instance is hosted on my server at home. Port forwarded and connection made through a Cloudflare tunnel. 

Here is a download link to my .minecraft folder that is being launched. https://drive.proton.me/urls/EV5R0FTZVR#Urg3Yf2yxpym

### BetterEnd

3.1.1

### BCLib

2.2.3

### Fabric API

0.70.0

### Fabric Loader

0.14.12

### Minecraft

1.19.3

### Relevant log output

```shell
[20:41:15] [Render thread/ERROR]: [worlds_together] Tried to read from global registry!
[20:41:15] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because the return value of "org.betterx.worlds.together.world.event.WorldBootstrap.getLastRegistryAccessOrElseBuiltin()" is null
    at org.betterx.bclib.api.v2.levelgen.biomes.BiomeAPI.getRenderBiome(BiomeAPI.java:443) ~[bclib-2.2.3.jar:?]
    at org.betterx.bclib.client.render.CustomFogRenderer.shouldIgnore(CustomFogRenderer.java:120) ~[bclib-2.2.3.jar:?]
    at org.betterx.bclib.client.render.CustomFogRenderer.shouldIgnoreArea(CustomFogRenderer.java:110) ~[bclib-2.2.3.jar:?]
    at org.betterx.bclib.client.render.CustomFogRenderer.applyFogDensity(CustomFogRenderer.java:42) ~[bclib-2.2.3.jar:?]
    at net.minecraft.client.render.BackgroundRenderer.handler$zdm000$bclib_fogDensity(BackgroundRenderer.java:569) ~[client-intermediary.jar:?]
    at net.minecraft.class_758.method_3211(class_758.java) ~[client-intermediary.jar:?]
    at net.minecraft.client.render.WorldRenderer.method_37365(WorldRenderer.java:1234) ~[client-intermediary.jar:?]
    at net.minecraft.client.render.WorldRenderer.renderSky(WorldRenderer.java:2004) ~[client-intermediary.jar:?]
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1234) ~[client-intermediary.jar:?]
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1085) ~[client-intermediary.jar:?]
    at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:864) ~[client-intermediary.jar:?]
    at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1193) ~[client-intermediary.jar:?]
    at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:781) ~[client-intermediary.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

### Other Mods

```shell
Server: bclib-2.2.3.jar  better-end-3.1.1.jar  fabric-api-0.70.0+1.19.3.jar  lithium-fabric-mc1.19.3-0.10.4.jar  memoryleakfix-1.19.3-0.7.0.jar  plasmovoice-fabric-1.19.3-1.2.19.jar  starlight-1.1.1+fabric.ae22326.jar

Client(s): 3dskinlayers-fabric-1.5.2-mc1.19.3.jar          iris-mc1.19.3-1.4.6.jar
bclib-2.2.3.jar                                 lambdynamiclights-2.2.0+1.19.3.jar
better-end-3.1.1.jar                            lazydfu-0.1.3.jar
bettermounthud-1.2.1.jar                        lithium-fabric-mc1.19.3-0.10.4.jar
borderless-mining-1.1.6+1.19.3.jar              modmenu-5.0.2.jar
cloth-config-9.0.94-fabric.jar                  MouseTweaks-fabric-mc1.19.3-2.24.jar
dynamic-fps-2.2.0.jar                           mousewheelie-1.10.6+mc1.19.3.jar
eating-animation-1.9.1.jar                      plasmovoice-fabric-1.19.3-1.2.19.jar
entityculling-fabric-1.5.2-mc1.19.3.jar         reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
exordium-fabric-1.0.3-mc1.19.3.jar              sodium-extra-0.4.15+mc1.19.3-build.86.jar
fabric-api-0.70.0+1.19.3.jar                    sodium-fabric-mc1.19.3-0.4.6+build.20.jar
fabric-language-kotlin-1.8.7+kotlin.1.7.22.jar  starlight-1.1.1+fabric.ae22326.jar
ferritecore-5.1.0-fabric.jar                    YetAnotherConfigLib-2.2.0.jar
indium-1.0.10+mc1.19.3.jar                      Zoomify-2.9.2.jar
```

**Comment by kraftdeaner** [comment]
im getting the same issue, deleted all of my mods besides fabapi & bclib & betterend with same results

**Comment by purejosh** [comment]
Please provide the entire crash log, or latest log.

**Comment by EmetDuncan** [comment]
[crash-2023-01-06_16.59.04-client.txt](https://github.com/quiqueck/BetterEnd/files/10363379/crash-2023-01-06_16.59.04-client.txt)
Started a LAN server. Host is fine but client will crash when conneted. This only happenes with BCLib or any BetterX mods enabled. 

BetterEnd
3.1.1
BetterNether
8.1.2
BCLib
2.2.3
Fabric API
0.71.0
Fabric Loader
0.14.12
Minecraft
1.19.3

**Comment by JosephTheMan** [comment]
I have the same problem.

**Comment by quiqueck** [comment]
Should be fixed with the next BCLib update.
