### ISSUE TITLE
[Bug] Internal server error on player enter Eternal Portal

### ISSUE THREAD

**Issue by ACNONE** [quiqueck/BetterEnd#140]
### What happened?

When I enter the lighted eternal portal, the game breaks down and I can't enter the world because of the Internal Server Error

### BetterEnd

2.1.3

### BCLib

2.1.5

### Fabric API

0.73.0

### Fabric Loader

0.14.13

### Minecraft

1.19.2

### Relevant log output

```shell
[13:27:18] [Server thread/INFO]: [Yay: Set own game mode to Creative Mode]
[13:28:14] [Server thread/INFO]: Yay has made the advancement [Eternal Light]
[13:28:14] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 8562ms or 171 ticks behind
[13:28:14] [Server thread/WARN]: Yay moved too quickly! -8.550185854256824,3.1077940961832127,-4.5435277556430265
[13:28:21] [Server thread/INFO]: [bclib] Checking class_2339{x=-753, y=92, z=-1184} for Portal
[13:28:22] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2828$class_2830@2a5827da, suppressing error
net.minecraft.class_148: Colliding entity with block
        at net.minecraft.class_1297.method_36974(class_1297.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12063(class_3244.java:965) ~[server-intermediary.jar:?]
        at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[server-intermediary.jar:?]
        at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:16) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
        at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
        at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_36974(class_1297.java:783) ~[server-intermediary.jar:?]
        ... 18 more
[13:28:22] [Server thread/INFO]: [bclib] Checking class_2339{x=-753, y=92, z=-1184} for Portal
[13:28:23] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:63559
net.minecraft.class_148: Colliding entity with block
        at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
        at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
        at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_36974(class_1297.java:783) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_26318(class_1309.java:2282) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6091(class_1309.java:2227) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6091(class_1657.java:1638) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6007(class_1309.java:2680) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:570) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
        ... 9 more
```

### Other Mods

```shell
ad_astra-fabric-1.19.2-1.12.2
AE2WTLib-12.8.5
antighost-1.19.1-fabric0.58.5-1.1.5
appliedenergistics2-fabric-12.9.2
architectury-6.4.62-fabric
bclib-2.1.5
better-end-2.1.3
better-nether-7.1.2
betteranimalsplus-1.19.2-11.0.10-fabric
BetterAnimationsCollection-v4.0.5-1.19.2-Fabric
botarium-fabric-1.19.2-1.8.2
Chunk+Pregenerator-1.19-4.1.1
create-fabric-0.5.0g-796+1.19.2
createaddition+1.19.2-1.19.2-20221218a
createdeco-1.2.12-1.19.2
entityculling-fabric-1.5.2-mc1.19
fabric-api-0.73.0+1.19.2
fabric-end-remastered-5.2.0
farmers-delight-fabric-1.19.X-1.3.9
ftb-chunks-fabric-1902.3.14-build.218
ftb-library-fabric-1902.3.11-build.166
ftb-teams-fabric-1902.2.12-build.95
geckolib-fabric-1.19-3.1.38
InventorySorter-1.8.10-1.19
jmi-fabric-1.19.2-0.13-30
journeymap-1.19.2-5.9.2-fabric
lithium-fabric-mc1.19.2-0.10.4
mcw-bridges-2.0.6-mc1.19.2fabric
mcw-lights-1.0.5-mc1.19.2fabric
mcw-trapdoors-1.0.8-mc1.19.2fabric
mcw-windows-2.1.2-mc1.19.2fabric
megacells-fabric-2.0.0-beta.6-1.19.2
naturalist-fabric-2.1.1-1.19.2
phosphor-fabric-mc1.19.x-0.8.1 (1)
PuzzlesLib-v4.3.12-1.19.2-Fabric
resourcefulconfig-fabric-1.19.2-1.0.18
resourcefullib-1.1.20 (1)
smoothchunk-1.19.1-2.0
Structory-1.19-v1.3
TechReborn-5.4.0
Terralith_v2.3.6
Towns-and-Towers-v.1.10.1-FABRIC-1.19.2
twilightforest-fabric-1.19.2-4.2.333
VisualWorkbench-v4.2.1-1.19.2-Fabric
voicechat-fabric-1.19.2-2.3.28
```

**Comment by BloodStalker52** [comment]
Same thing is happening with myself and a friend on my server with Better MC Fabric BMC1 V14 modpack

**Comment by ghost** [comment]
Same issue here, except I changed the portal config to take the player to Eden Ring instead of the overworld. Tested in a fresh instance with only BetterEnd, Eden Ring, BCLib, and Fabric API. [Crash report](https://gist.github.com/Puffadillo/9c7fc82eb07b091eccc6b6e905c1d3ed)

Oddly enough, I tested this on my primary in-development modpack which has 96 _more_ mods, and it works without crashing. The configs for both packs should be the same, so this is definitely strange. Here's the [latest log](https://gist.github.com/Puffadillo/2e9c2a3f7b848438ee22be00ae307c45) from that pack, if it'd be of any use.

**Edit**: Can confirm that I had version 2.1.3 when crashing, and 2.1.2 when the portal was working fine. Likely the same problem as the commenter below me.

**Comment by genki-angel** [comment]
I have also been getting the same issue and with a similar [crash log](https://gist.github.com/genki-angel/270e259a5a7253040e6a84adcca1a381). This happens to me when using v2.1.3,  downgrading to 2.1.2 has stopped the portal from crashing for me. 
It looks like it is related to this [commit](https://github.com/quiqueck/BetterEnd/commit/01f9148c5ce51baef50ed3d449cd821a29391035) here.

**Comment by suerion** [comment]
Hey, Same issue here -> 

 ```(Logger) [bclib] Checking class_2339{x=1088, y=70, z=-128} for Portal
[17:10:06] [Server thread/WARN] (class_3242) Failed to handle packet for /178.251.68.247:60355
net.minecraft.class_148: Colliding entity with block
        at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bhd000$modifiedRunLoop(MinecraftServer.java:7885) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
        at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
        at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.redirect$cpf000$checkBlockCollisionBetter(class_1297.java:13132) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.redirect$cpf000$onEntityCollision(class_1297.java:13100) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_26318(class_1309.java:2282) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6091(class_1309.java:2227) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6091(class_1657.java:1638) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6007(class_1309.java:2680) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:570) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
        ... 10 more
[17:10:07] [Server thread/INFO] (Logger) [bclib] Checking class_2339{x=1088, y=70, z=-128} for Portal
[17:10:07] [Server thread/WARN] (class_3242) Failed to handle packet for /178.251.68.247:60355
net.minecraft.class_148: Colliding entity with block
        at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bhd000$modifiedRunLoop(MinecraftServer.java:7885) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
        at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
        at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
        at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.redirect$cpf000$checkBlockCollisionBetter(class_1297.java:13132) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.redirect$cpf000$onEntityCollision(class_1297.java:13100) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_26318(class_1309.java:2282) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6091(class_1309.java:2227) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6091(class_1657.java:1638) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6007(class_1309.java:2680) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:570) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
        ... 10 more```

**Comment by RhinoInquiring** [comment]
ditto but I haven't changed the configs.

[crash-2023-02-05_13.10.08-server.txt](https://github.com/quiqueck/BetterEnd/files/10614083/crash-2023-02-05_13.10.08-server.txt)

**Comment by purejosh** [comment]
I'm running stock configs, and this is happening on my server as well.

**Comment by quiqueck** [comment]
Hi, did you check that all mod versions are the same on client and server (BCLib and BetterEnd)? The missing method from the log sounds a bit like an outdated bclib version...

**Comment by quiqueck** [comment]
Ah, found it. Sorry the needed change to BCLib did not make it to the latest BCLib release somehow. Will update soon.
