### ISSUE TITLE
[Bug] Dashloader and better end/nether are having compatibility issues.

### ISSUE THREAD

**Issue by 1GladCat** [quiqueck/BetterEnd#149]
### What happened?

when booting up with dashloader and better end/nether installed it dashloader says "there is an internal error".

### BetterEnd

3.1.2

### BCLib

2.2.4

### Fabric API

0.73.0

### Fabric Loader

0.14.14

### Minecraft

1.19.3

### Relevant log output

```shell
[01:12:13] [dashloader-thread/INFO]: Starting DashLoader Caching
[01:12:13] [dashloader-thread/INFO]: Checking for cache count.
[01:12:13] [dashloader-thread/ERROR]: Could not enforce maximum cache 
java.nio.file.NoSuchFileException: .\dashloader-cache\client\585D04F95CEA908D738AF68B8C0AB43F
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:535) ~[?:?]
	at java.nio.file.Files.newDirectoryStream(Files.java:482) ~[?:?]
	at java.nio.file.Files.list(Files.java:3792) ~[?:?]
	at dev.notalpha.dashloader.Cache.save(Cache.java:78) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at net.minecraft.class_425.md279af7$lambda$done$1$0(class_425.java:2076) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:12:13] [dashloader-thread/ERROR]: Failed caching
java.lang.RuntimeException: Could not create DashObject class_1095
	at dev.notalpha.dashloader.registry.FactoryBinding.create(FactoryBinding.java:44) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.data.ChunkFactory.create(ChunkFactory.java:31) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryFactory.lambda$add$0(RegistryFactory.java:73) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryWriter.create(RegistryWriter.java:33) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryFactory.add(RegistryFactory.java:72) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.client.model.ModelModule.lambda$save$0(ModelModule.java:57) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.quantumfusion.taski.builtin.StepTask.lambda$doForEach$1(StepTask.java:143) ~[dev_quantumfusion_taski-2.1.0-96b67398e178a8d3.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at dev.quantumfusion.taski.builtin.StepTask.doForEach(StepTask.java:142) ~[dev_quantumfusion_taski-2.1.0-96b67398e178a8d3.jar:?]
	at dev.notalpha.dashloader.client.model.ModelModule.save(ModelModule.java:54) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.client.model.ModelModule.save(ModelModule.java:30) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.io.MappingSerializer.save(MappingSerializer.java:48) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.Cache.save(Cache.java:128) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at net.minecraft.class_425.md279af7$lambda$done$1$0(class_425.java:2076) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: someone is having fun with lambda selectors again
	at dev.notalpha.dashloader.client.DashLoaderClient.lambda$onDashLoaderSave$1(DashLoaderClient.java:111) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryFactory.lambda$add$1(RegistryFactory.java:84) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryWriter.create(RegistryWriter.java:33) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryFactory.add(RegistryFactory.java:83) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryWriter.add(RegistryWriter.java:26) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.client.model.DashMultipartBakedModel.<init>(DashMultipartBakedModel.java:48) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.FactoryBinding$InvokeType.lambda$static$0(FactoryBinding.java:72) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.FactoryBinding.create(FactoryBinding.java:42) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	... 14 more
[01:12:13] [dashloader-thread/INFO]: [46m[30m DashLoader Status change IDLE
```

### Other Mods

```shell
dashloader-5.0.0-alpha.9+1.19.3
```

**Comment by quiqueck** [comment]
Hi, and thanks for reporting?
before we start, did you already report this to the DashLoader Team, and if so could you please link to the issue?

**Comment by 1GladCat** [comment]
I have not reported it yet but i porbably should.

Edit1: Here it is: https://github.com/TeamQuantumFusion/DashLoader/issues/55

Edit2: They finally responded

**Comment by quiqueck** [comment]
Unfortunatley I still do not know what it is that needs fixing on our end. So unfortunately I can not help with this issue :(
