### ISSUE TITLE
Entering Eternal Portal crashes game

### ISSUE THREAD

**Issue by Awesome23rd** [quiqueck/BetterEnd#151]
### What happened?

When i walk through the Eternal Portal after activating it with the crystals my game crashes.

### BetterEnd

2.1.3

### BCLib

2.1.5

### Fabric API

0.73.2

### Fabric Loader

0.14.14

### Minecraft

1.19.2

### Relevant log output

```shell
exit code: -1
crash text:
The game crashed whilst colliding entity with block
Error: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'

crash log:
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2023-02-12 15:38:22
Description: Colliding entity with block

java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
	at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783)
	at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733)
	at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169)
	at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952)
	at net.minecraft.class_1297.method_5852(class_1297.java:1059)
	at net.minecraft.class_1297.method_36974(class_1297.java:783)
	at net.minecraft.class_1297.method_5784(class_1297.java:752)
	at net.minecraft.class_1309.method_26318(class_1309.java:2282)
	at net.minecraft.class_1309.method_6091(class_1309.java:2227)
	at net.minecraft.class_1657.method_6091(class_1657.java:1638)
	at net.minecraft.class_1309.method_6007(class_1309.java:2680)
	at net.minecraft.class_1657.method_6007(class_1657.java:570)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)
	at net.minecraft.class_3222.method_14226(class_3222.java:487)
	at net.minecraft.class_3244.method_18784(class_3244.java:268)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Other Mods

```shell
Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.4
		ambientenvironment: Ambient Environment 8.0+3
		amplifiednether: Amplified nether 1.2
		appleskin: AppleSkin 2.4.1+mc1.19
		balm-fabric: Balm 4.5.2+0
		bclib: BCLib 2.1.5
		beaconoverhaul: Beacon Overhaul 1.7.3+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		better_climbing: Better Climbing 1.1.0
		betteranimationscollection: Better Animations Collection 4.0.5
		bettercombat: Better Combat 1.5.5+1.19
		betterend: Better End 2.1.3
		bettermounthud: Better Mount HUD 1.2.0
		betternether: Better Nether 7.1.2
		betterthanmending: BetterThanMending 1.3.0
		betterthirdperson: Better Third Person 1.9.0
		bookshelf: Bookshelf 16.2.17
		campanion: Campanion 4.1.2+fabric
		caveore: Cave Spelunking 1.19-2.4
		chas: Craftable Horse Armour & Saddle 1.19-1.9-Fabric
		chefsdelight: Chef's Delight 1.0.2-fabric-1.19.2
			structurized-reborn: Structurized Reborn 1.19-01
		chimes: Chimes 1.1.4
		chunksfadein: Chunks Fade In 3.0.8-1.19
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cinderscapes: Cinderscapes 3.0.3
			cinderscapes-client: Cinderscapes: Client 3.0.3
			cinderscapes-common: Cinderscapes: Common 3.0.3
			cinderscapes-worldgen: Cinderscapes: World Generation 3.0.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.1.1
		cleardespawn: Clear Despawn 1.1.10
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		clumps: Clumps 9.0.0+14
		collective: Collective 6.43
		combatroll: Combat Roll 1.1.2+1.19
		connectiblechains: Connectible Chains 2.1.4+1.19.2
		controlling: Controlling For Fabric 10.0+7
		couplings: Couplings 1.9.1+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		criticalib: CriticaLib 1.0.0
		culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		damageindicator: Damage Indicator 1.0.0
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dawn: Dawn API 3.5.0
		deeperdarker: Deeper and Darker 1.1.6
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			paragon: Paragon 3.0.2
				blue_endless_jankson: jankson 1.2.1
				org_yaml_snakeyaml: snakeyaml 1.27
		effective: Effective 1.4
			midnightlib: MidnightLib 0.5.2
		elytra_physics: ElytraPhysics 1.1.1
		emeraldapple: Emerald Apple 1.0.3
		enchdesc: EnchantmentDescriptions 13.0.14
		enderchests: EnderChests 1.1.1
		enderscape: Enderscape 0.4.1-1.19.2
			mm: Manningham Mills 2.3
		endrem: End Remastered 5.2.0
		expandeddelight: Expanded Delight 0.2.5.1
		fabric-api: Fabric API 0.73.2+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.24+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.1+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		fdjei: Just Enough Farmer's Recipes 1.0.1
		firstperson: FirstpersonModel 2.2.0
		forgeconfigapiport: Forge Config API Port 4.2.10
		geckolib3: Geckolib 3.1.38
			com_eliotlash_mclib_mclib: mclib 20
		graveyard: The Graveyard 2.3
			omega-config: OmegaConfig 1.2.2-1.18.1
		graveyard_biomes: The Graveyard Biomes 1.6
		healthbarplus: Health Bar Plus 1.0.1
		herdspanic: Herds Panic 1.0.6
		hw_do: Higher World Deeper Oceans 0.0.1
		ice_boat_nerf: Ice Boat Nerf 1.0.13
		indium: Indium 1.0.9+mc1.19.2
		interactic: Interactic 0.1.11+1.19
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.5.2.1007
		jeresources: Just Enough Resources 1.2.1.189
		justenoughprofessions: Just Enough Professions (JEP) 2.0.1
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		libertyvillagers: Liberty's Villagers 1.0.13+fabric+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		limitedspawners: Limited Spawner 1.0.6
		lod: Distant Horizons 1.6.9a
		maptooltip: Map Tooltip 2.0.0
		mcda: MC Dungeons Armors 2.4.2
		mcdw: MC Dungeons Weapons 5.0.4-1.19
			enchant_giver: Enchant Giver 1.3.0
		medievalweapons: Medieval Weapons 1.4.2
		minecraft: Minecraft 1.19.2
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		mixintrace: MixinTrace 1.1.1+1.17
		mob_catcher: Mob Catcher 1.2.15
		modmenu: Mod Menu 4.1.2
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		mushroom: Mushroom Update 1.0.0
		mythicmounts: Mythic Mounts 1.19.2-7.1
		mythicupgrades: Mythic Upgrades 1.5
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		netherdepthsupgrade: Nether Depths Upgrade fabric-2.0.4-1.19.2
		netherportalfix: NetherPortalFix 10.0.0
		nethersdelight: Nether's Delight 1.0.1
			disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		netherwardblock: Nether Wart Block to Nether Warts 1.19.2-6
		notenoughanimations: NotEnoughAnimations 1.6.2
		notenoughbreeding: Not Enough Breeding 1.19.2-1.0.0-fabric
		npcvariety: NPC Variety 2.2.2
		nyfsquiver: Nyf's Quivers Fabric-0.5.1-1.19.2
			trinkets: Trinkets 3.5.0
		oxirods: Oxidized Lightning Rod  1.19.2-5
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		physicsmod: Physics Mod 2.10.2
		pickupnotifier: Pick Up Notifier 4.2.0
		ping-wheel: Ping Wheel 1.2.0
		player-animator: Player Animator 0.4.2
		presencefootsteps: Presence Footsteps 1.6.4
			kirin: Kirin UI 1.11.1
		probablychests: Probably Chests 0.5.5-1.19.2
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		riverredux: River Redux 0.3.0
		satin: Satin 1.9.0
		shetiphiancore: ShetiPhianCore 1.3.4
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		smallships: Small Ships 2.0.0a1.1.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		soulsweapons: Marium's Soulslike Weaponry 0.9.8
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spiderstpo: Spiders 2.0 1.19.2-2.0.3
		stoneholm: Stoneholm 1.4.4
		stylisheffects: Stylish Effects 4.3.2
		terrablender: TerraBlender 2.0.1.130
		terralith: Terralith 2.3
		third_person_maps: Third Person Maps 1.4.0
		transportables: Transportables 1.2.1
		traverse: Traverse 6.0.6
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 4.2.0
			terraform-config-api-v1: Terraform Config API (v1) 4.2.0
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 4.2.0
			terraform-tree-api-v1: Terraform Tree API (v1) 4.2.0
			traverse-client: Traverse: Client 6.0.6
			traverse-common: Traverse: Common 6.0.6
			traverse-worldgen: Traverse: World Generation 6.0.6
		twilightforest: The Twilight Forest 4.2.335
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			porting_lib: Porting Lib 2.1.727+1.19.2
				com_github_llamalad7_mixinextras: MixinExtras 0.1.1
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.727+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.727+1.19.2
				porting_lib_base: Porting Lib Base 2.1.727+1.19.2
				porting_lib_common: Porting Lib Common 2.1.727+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.727+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.727+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.727+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.727+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.727+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.727+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.727+1.19.2
				porting_lib_models: Porting Lib Models 2.1.727+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.727+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.727+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.727+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
		universal_ores: Universal Ores 1.4.2
		universalbonemeal: Universal Bone Meal 4.2.0
		universalenchants: Universal Enchants 4.2.14
			extensibleenums: Extensible Enums 4.0.0
		unwrecked-ships: Unwrecked Ships 0.0.3
		villager_see_villager_do: Villager See, Villager Do 1.1.8
			crowdin-translate: CrowdinTranslate 1.4+1.19
		villagerfix: Villager Trade Fix 1.0.3
		villagernames: Villager Names 5.1
```

**Comment by Flyvee** [comment]
I got the same issue on my server where another player entered the eternal portal from the end side which caused them to crash, they could only safely log back in after I've removed one of the crystals and deactivated the portal, they then logged back in in crawling position inside the portal still on the end side, this is the error the server gave:
[12.02 19:53:31] [Server] [Server thread/WARN]: Failed to handle packet for /70.95.105.218:64351
[12.02 19:53:31] [Server] net.minecraft.class_Colliding entity with block
[12.02 19:53:31] [Server] 	at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[12.02 19:53:31] [Server] Caused byjava.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
[12.02 19:53:31] [Server] 	at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
[12.02 19:53:31] [Server] 	at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
[12.02 19:53:31] [Server] 	at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
[12.02 19:53:31] [Server] 	at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1297.method_36974(class_1297.java:783) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1309.method_26318(class_1309.java:2282) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1309.method_6091(class_1309.java:2227) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1657.method_6091(class_1657.java:1638) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1309.method_6007(class_1309.java:2680) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1657.method_6007(class_1657.java:570) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
[12.02 19:53:31] [Server] 	... more
[12.02 19:53:31] [Disconnect] Chev_Fam has disconnected, reasonInternal server error

**Comment by linkbeta5** [comment]
My server had the same issue, I'll see if I can get someone to remove the crystals but I think our admin's reverting our save file here soon. Is there anyway to fix this at all??

**Comment by Flyvee** [comment]
While removing the crystal restores the player from crashing but for now, downgrading to the previous version will prob help if your server is actively using the eternal portals.

**Comment by Benubisnitch** [comment]
Also having this issue. Using the Better MC Modpack and getting this crash. 1.19.2
https://pastebin.com/4740PPie
