### ISSUE TITLE
[Bug] Game crashes on startup when items are disabled

### ISSUE THREAD

**Issue by LucasOe** [quiqueck/BetterEnd#166]
### What happened?

When the option `"guidebook [default: true]": false` is set inside `items.json`, the game crashes on startup. The crash only happens when Patchouli is installed.

Edit: I've just noticed this doesn't only happen with the guidebook. When I disable any items in general the game crashes on startup.

### BetterEnd

2.1.4

### BCLib

2.1.6

### Fabric API

0.73.2

### Fabric Loader

0.14.14

### Minecraft

1.19.2

### Relevant log output

```shell
[20:57:10] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:352) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$bac001$onStart(class_310.java:6986) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:747) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
[20:57:10] [Render thread/INFO]: Stopping!
[20:57:10] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1092) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1068) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:260) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
```

### Other Mods

```shell
Full modlist:
	- architectury 6.5.69
	- bclib 2.1.6
	- betterend 2.1.4
	- emi 0.6.5+1.19.2
	- fabric-api 0.73.2+1.19.2
	- fabricloader 0.14.14
	- kubejs 1902.6.0-build.140
	- minecraft 1.19.2
	- patchouli 1.19.2-77-FABRIC
	- rhino 1902.2.2-build.264
```

**Comment by ginsm** [comment]
I'm having this same issue. I installed the mod, its dependency, fabric api on a fresh instance (via the CurseForge app) and then configured it; I did this to ensure nothing else would be causing the issue.

**Minecraft:** `1.19.2`
**BetterEnd:** `2.1.4`
**BCLib:** `2.1.6`
**Fabric API:** `0.75.1+1.19.2`
**Fabric Loader:** `0.14.14`

Here's the [items.json](https://pastebin.com/t8t3GF87) and [recipes.json](https://pastebin.com/sLAewVY2) I used. I configured the `recipes.json` to remove any recipes which contained disabled items. And here's the resulting [log](https://pastebin.com/Jby3n292).
