### ISSUE TITLE
[Bug] cant join server after entering eternal ruins portal

### ISSUE THREAD

**Issue by AnselmKoch** [quiqueck/BetterEnd#179]
### What happened?

A friend put the eternal ruins portal together and entered it.
After that he constantly gets kicked out of the server with the message "Internal Server Errror". Everytime he logs in he gets kicked with the same message again.
Thats what the Console says:

### BetterEnd

2.1.3

### BCLib

2.1.5

### Fabric API

0.73.2+

### Minecraft

1.19.2

### Relevant log output

 [08:51:42] [Server thread/INFO]: Handshake succeeded with no issues
[08:51:42] [Server thread/INFO]: [bclib] Checking class_2339{x=-1232, y=85, z=336} for Portal
[08:51:42] [Server thread/WARN]: Failed to handle packet for /178.2.237.135:58728
net.minecraft.class_148: Colliding entity with block
	at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'
	at org.betterx.betterend.rituals.EternalRitual.findClosestPoi(EternalRitual.java:783) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.rituals.EternalRitual.findBlockPos(EternalRitual.java:733) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.blocks.EndPortalBlock.findExitPos(EndPortalBlock.java:169) ~[better-end-2.1.3.jar:?]
	at org.betterx.betterend.blocks.EndPortalBlock.method_9548(EndPortalBlock.java:115) ~[better-end-2.1.3.jar:?]
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_36974(class_1297.java:783) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_26318(class_1309.java:2282) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6091(class_1309.java:2227) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6091(class_1657.java:1638) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2680) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:570) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
	... 9 more

### Other Mods

Entite Better Vanilla MC Modpack (Version 1.19.2)

**Comment by AnselmKoch** [comment]
After changing the players position via NBTExplorerer he can now join again. The collition with the portal block was the problem

**Comment by AmayaValkyria** [comment]
A friend and I have the same problem with the portal. We solved it the same way you did. Is it now safe to go through or does the error come up again?

Also, my friend accidentally dropped a block into the portal in the overworld, which then broke the entire server.
We play Better Minecraft [FABRIC] v15 (Minecraft 1.19.2)

[crash-2023-03-13_19.29.13-server.txt](https://github.com/quiqueck/BetterEnd/files/10962424/crash-2023-03-13_19.29.13-server.txt)
