### ISSUE TITLE
[Bug] java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap

### ISSUE THREAD

**Issue by faiks39847** [quiqueck/BetterEnd#204]
### What happened?

Hello, there was a problem when trying to download End via Chunky
Crash-report:

### BetterEnd

2.1.4

### BCLib

2.1.6

### Fabric API

0.76.0

### Fabric Loader

0.14.19

### Minecraft

1.19.2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-04-26 01:24:08
Description: Feature placement

java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1986)
	at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2102)
	at java.base/java.util.HashMap$TreeNode.split(HashMap.java:2322)
	at java.base/java.util.HashMap.resize(HashMap.java:712)
	at java.base/java.util.HashMap.putVal(HashMap.java:661)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeight(MountainPiece.java:94)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeightClamp(MountainPiece.java:133)
	at org.betterx.betterend.world.structures.piece.PaintedMountainPiece.method_14931(PaintedMountainPiece.java:102)
	at net.minecraft.class_3449.method_14974(class_3449.java:99)
	at net.minecraft.class_2794.method_38265(class_2794.java:429)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:428)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.mddb1510$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1986)
	at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2102)
	at java.base/java.util.HashMap$TreeNode.split(HashMap.java:2322)
	at java.base/java.util.HashMap.resize(HashMap.java:712)
	at java.base/java.util.HashMap.putVal(HashMap.java:661)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeight(MountainPiece.java:94)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeightClamp(MountainPiece.java:133)
	at org.betterx.betterend.world.structures.piece.PaintedMountainPiece.method_14931(PaintedMountainPiece.java:102)
	at net.minecraft.class_3449.method_14974(class_3449.java:99)
	at net.minecraft.class_2794.method_38265(class_2794.java:429)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:428)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.mddb1510$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

-- Feature --
Details:
	Description: ResourceKey[minecraft:worldgen/structure / betterend:painted_mountain]
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:428)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.mddb1510$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Generation --
Details:
	CenterX: -131
	CenterZ: -87
	Seed: 2430303477696027950
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:428)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.mddb1510$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Wrapped in --
Details:
	Wrapping exception: ~~ERROR~~ CompletionException: net.minecraft.class_148: Feature placement
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_40376(MinecraftServer.java:723)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:682)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.1.0-7-amd64
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 9010448344 bytes (8593 MiB) / 10737418240 bytes (10240 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: HD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x5912
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 64777.36
	Virtual memory used (MB): 59053.04
	Swap memory total (MB): 32735.00
	Swap memory used (MB): 3267.00
	JVM Flags: 21 total; -Xms10G -Xmx10G -XX:+IgnoreUnrecognizedVMOptions -XX:+UseConcMarkSweepGC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		balm-fabric: Balm 4.5.7
		bclib: BCLib 2.1.6
		betterend: Better End 2.1.4
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.3
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.9.9
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.9.9
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.9.9
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.9.9
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.9.9
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.9.9
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.9.9
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.9.9
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.9.9
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.9.9
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.9.9
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.9.9
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.9.9
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.9.9
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.9.9
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.9.9
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.9
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.9.9
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.9.9
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.9
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chisel: Chisel Refabricated 1.4.5
		chunky: Chunky 1.3.38
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.0.i-991+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 4.2.9
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.875+1.19.2
				forge_tags: Porting Lib Tags 3.0
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 2.1.875+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.875+1.19.2
				porting_lib_base: Porting Lib Base 2.1.875+1.19.2
				porting_lib_common: Porting Lib Common 2.1.875+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.875+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.875+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.875+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.875+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.875+1.19.2
				porting_lib_loot: Porting Lib Loot 2.1.875+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.875+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.875+1.19.2
				porting_lib_models: Porting Lib Models 2.1.875+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.875+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.875+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.875+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.57-MC1.19.2
		createaddition: Create Crafts & Additions 20230211a
			team_reborn_energy: Energy 2.2.0
		diggusmaximus: Diggus Maximus 1.5.8-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		dungeon_now_loading: dungeon-now-loading-18.2 1.0.0
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.19
		fabricproxy-lite: FabricProxy Lite 2.3.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		fastload: Fast Load 3.3.0
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.3.0
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.3.0
			fastload-1194-compat: Fastload 1.19.4 Compat 3.3.0
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.1
		ferritecore: FerriteCore 5.0.3
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 11.5.2.1007
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		ledger: Ledger 1.2.5
			server_translations_api: Server Translations API 1.4.14+1.19-rc2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		ledger-databases: Ledger Databases 1.1.1
			com_h2database_h2: h2 1.4.200
			mysql_mysql-connector-java: mysql-connector-java 8.0.19
			org_postgresql_postgresql: postgresql 42.3.0
		lithium: Lithium 0.11.1
		mcwdoors: Macaw's Doors 1.0.8
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		minecraft: Minecraft 1.19.2
		moonlight: Moonlight 1.19.2-2.2.29
		naturalist: Naturalist 3.0.2
		nethersdelight: Nether's Delight 1.0.1
		plasmovoice: Plasmo Voice 2.0.3
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			javax_inject_javax_inject: javax.inject 1
			universalcraft: UniversalCraft 262
			ustats: uStats 1.0.0
		rprenames: RP Renames 0.2.0
			libgui: LibGui 6.4.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		servercore: ServerCore 1.3.3-1.19.2
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
		smoothboot: Smooth Boot 1.19-1.7.1
		spark: spark 1.10.34
		starlight: Starlight 1.1.1+fabric.ae22326
		supplementaries: Supplementaries 1.19.2-2.3.4
		vmp: Very Many Players 0.2.0+beta.7.29
		waystones: Waystones 11.3.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
	Server Running: true
	Player Count: 1 / 20; [class_3222['faiks12'/93, l='ServerLevel[world]', x=-85.86, y=5.50, z=-42.58]]
	Data Packs: vanilla, Fabric Mods, Supplementaries Generated Pack
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by quiqueck** [comment]
Hm, that is a strange crash. I would guess that it is caused in combination with Concurrent Chunk Management Engine, as the error does only make sense as a side effect of a race condition.

Could you maybe try again without Concurrent Chunk Management Engine?

**Comment by JiDW** [comment]
Hello!

I can confirm this issue is indeed related to C2ME.

Do you think a compatibility would be possible at some point?

Here are all the info I can bring:

- The crashes are always about the same type of stacktrace. 
- The C2ME devs think it can only be modified on BetterEnd side ( https://github.com/RelativityMC/C2ME-fabric/issues/236 )
- I'm adding a server log and a crash report for the same crash event

[2023-10-09-1.log](https://github.com/quiqueck/BetterEnd/files/12849410/2023-10-09-1.log)
[crash-2023-10-09_00.12.58-server.txt](https://github.com/quiqueck/BetterEnd/files/12849411/crash-2023-10-09_00.12.58-server.txt)

Let me know if I can help with anything.

**Comment by votetheremess** [comment]
This crash is most likely the same root cause as #594: LakePiece and MountainPiece keep their height caches in a plain HashMap that is shared by every chunk the structure spans. Parallel chunk generation (Chunky pregeneration plus c2me in your case) corrupts the map. The ClassCastException here and the infinite loop in #594 are the two classic symptoms of concurrent HashMap corruption. Details, thread dumps, and a suggested one line fix are in #594.
