### ISSUE TITLE
[Bug] 1.19.2 tiny config change results to crash 

### ISSUE THREAD

**Issue by notIkibo** [quiqueck/BetterEnd#218]
### What happened?

I may have found the needle in the hay. I was making a modpack blablablabla.
pre-configurated stuff. Then exported it and tried importing it.
My modpack didn't work. That was really weird ngl. Because I changed nothing. No new mod, not anything.
I got this message at the end of my logs:
(look below)

Like it's basically indicating any imcompatibility. 
But: If I deleted the config folder: It worked.

Who would've thought that better end was the culprit.
I deleted a portion of the configs and looked at what exactly made it work and found out: Betterend was it.
So I worked with diffchecker and just looking at the sizes of the normal standard config and my "faulty" one.
There were some differences like "hasCentralIslands", but this wasn't game breaking.

guidebook is.
I turned off the guidebook in the configs completely and it broke minecraft singlehandedly.
That's....really interesting.

and I hope you can recreate it?
My modpack consists of around 200 mods. I obviously have Patchouli and nothing else really fiddles with guidebooks.

So yeah. Thank you for listening to my TED talk

### BetterEnd

2.1.5

### BCLib

2.1.6

### Fabric API

0.76.0

### Fabric Loader

0.14.19 to 21

### Minecraft

1.19.2

### Relevant log output

```shell
08:47:25] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:352) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$dki002$fabric-registry-sync-v0$onStart(class_310.java:18486) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:747) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
[08:47:25] [Render thread/INFO]: Stopping!
[08:47:25] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1092) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1068) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:260) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
```

### Other Mods

```shell
[08:56:03] [main/INFO]: Loading 359 mods:
	- additionaladditions 5.1.0
	- additionalbanners 10.1.7
	- additionalstructures 4.1.1
	- adorn 3.8.3+1.19.2
	- advanced_runtime_resource_pack 0.6.4
	- advdebug 2.3.0
	- adventurez 1.4.18
	- appleskin 2.4.1+mc1.19
	- arcanus 1.30
	- architectury 6.5.85
	- attributefix 17.2.6
	- axolotlitemfix 1.1.4
	- badpackets 0.2.1
	- balm-fabric 4.5.7
	- basicshields 1.4.0-1.19.2
	   \-- crowdin-translate 1.4+1.19
	- bclib 2.1.6
	- bedspreads 6.0.0+1.19.2
	- betteradvancements 0.3.0.148
	- betteranimalsplus 1.19.2-11.0.10
	- betteranimationscollection 4.0.5
	- betterend 2.1.5
	- bettermounthud 1.2.0
	- betterpingdisplay 1.1.1
	- betterstats 2.7.2+1.19.2
	   \-- tcdcommons 2.7+1.19.2
	- betterthanmending 1.3.0
	- betterthirdperson 1.9.0
	- biomeinfo 1.19.2-12
	- biomemakeover 1.19.2-1.6.4
	- blockus 2.5.10+1.19.2
	   \-- terraform-wood-api-v1 4.2.0
	- blur 2.6.0
	- bobby 4.0.1
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- bolt 1.2.1
	   \-- blue_endless_jankson 1.2.1
	- bookshelf 16.2.18
	- bosses_of_mass_destruction 1.4.6-1.19.2
	   |-- maelstrom_library 1.3-1.19-pre1
	   \-- multipart_entities 1.2-1.19-pre1
	- byg 2.0.1.1
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- cardinal-components 5.0.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-item 5.0.2
	   |-- cardinal-components-level 5.0.2
	   |-- cardinal-components-scoreboard 5.0.2
	   \-- cardinal-components-world 5.0.2
	- charm 4.4.4
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- charmonium 4.2.1
	- chat_heads 0.10.14
	- chubbystuff 2.0.1-fabric
	- cleancut 1.19.2-5.1-fabric
	- cleardespawn 1.1.10
	- clickthrough 1.19.1-fabric0.58.5-0.4
	   |-- crowdin-translate 1.4+1.19
	   \-- gbfabrictools 1.3.4+1.19
	- clienttweaks 8.1.2
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- collective 6.53
	- comforts 6.0.4+1.19.2
	   \-- spectrelib 0.12.4+1.19.2
	- configured 2.0.0
	- continents 1.1.2
	- controlling 10.0+7
	- corgilib 1.0.0.33
	- cosmetica 1.2.4
	   |-- com_github_cosmetica-cc_cosmeticadotjava 1.11.2
	   \-- sulphate 1.1.1
	- crafttweaker 10.1.44
	   |-- org_javassist_javassist 3.29.0-GA
	   \-- org_reflections_reflections 0.10.2
	- crawl 0.11.1
	   \-- mm 2.3
	- cull-less-leaves 1.0.6
	   \-- conditional-mixin 0.3.0
	- dark-loading-screen 1.6.12
	- darkpaintings 13.1.5
	- dashloader 4.1.3+1.19
	   |-- com_github_luben_zstd-jni 1.5.2-2
	   |-- dev_quantumfusion_hyphen 0.2.2
	   \-- dev_quantumfusion_taski 1.1.0
	- debugify 2.8.0
	- decorative_blocks 3.0.0
	- deeperdarker 1.1.6
	   |-- customportalapi 0.0.1-beta54-1.19
	   \-- paragon 3.0.2
	        \-- org_yaml_snakeyaml 1.27
	- deepslatecutting 1.5.0
	   \-- maybe-data 1.3.2-1.19.2
	- diagonalfences 4.2.5
	- dragonloot 1.1.2
	- duckling 2.0.8
	- dummmmmmy 1.19.2-1.7.1
	- earthtojavamobs 1.10.0
	- easymagic 4.3.3
	- easyshulkerboxes 4.4.0
	- ecologics 2.1.11
	- effective 1.4
	- elytraslot 6.1.1+1.19.2
	- emojiful 4.0.4
	   \-- com_esotericsoftware_yamlbeans_yamlbeans 1.15
	- enchdesc 13.0.14
	- endgoblintraders 1.5.2
	- enhanced_attack_indicator 1.0.4+1.19
	- entityculling 1.6.1-mc1.19.2
	- exordium 1.0.2-mc1.19.2
	- extended_armor_bars 1.2.1
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricenchantments 0.9.0
	- fabricloader 0.14.19
	- fabricshieldlib 1.7-1.19.2
	   \-- mm 2.3
	- fallingleaves 1.13.0+1.19.2
	- fallingtree 3.10.0
	- farsighted-mobs 1.1-1.18-1.19
	- faux-custom-entity-data 2.0.2
	- ferritecore 5.0.3
	- forgeconfigapiport 4.2.11
	- frame 0.26.1+1.19-fabric
	   |-- frame-api-base 0.2.1+906ebc04a9
	   |-- frame-blocks-v0 0.1.3+233e7428a9
	   |-- frame-config-v0 0.3.1+0fa45150a9
	   |-- frame-content-registries-v0 0.4.0+2876b511a9
	   |-- frame-enchantments-v0 0.1.0+4093105da9
	   |    \-- mm 2.3
	   |-- frame-game-rules-v0 0.2.4+e7ce56a6a9
	   |-- frame-items-v0 0.1.3+906ebc04a9
	   |-- frame-loot-tables-v0 0.1.4+4f7341eca9
	   |-- frame-registries-v0 0.1.1+0e0ec74ea9
	   |-- frame-rendering-v0 0.1.5+906ebc04a9
	   |-- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9
	   |-- frame-toymaker-v0 0.6.1+b13741c3a9
	   \-- frame-woods-v0 0.2.1+6a33fbada9
	- fwaystones 3.0.7+mc1.19.2
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- geodes 1.7+1.19
	- goblintraders 1.8.1
	- graveyard 2.3.2
	- grindenchantments 3.1.0+1.19.2
	   \-- codec-config-api 1.0.2+1.19.3
	- healthoverlay 7.2.4
	   \-- fiber 0.23.0-2
	- immediatelyfast 1.1.12
	   \-- net_lenni0451_reflect 1.1.0
	- immersive_armors 1.5.5+1.19.2
	- immersive_paintings 0.6.0+1.19.2
	- indium 1.0.9+mc1.19.2
	- ingredient-extension-api 3.0.6
	- inmis 2.7.1-1.19
	   \-- omega-config 1.2.3-1.18.1
	- inventoryhud 3.4.7
	- inventorysorter 1.8.10-1.19
	   \-- kyrptconfig 1.4.14-1.19
	- iris 1.6.2
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 8.7.3
	- jadeaddons 3.1.0
	- jamlib 0.6.0+1.19
	- java 17
	- jmi 0.13-33
	- journeymap 5.9.7
	   \-- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT
	- kiwi 8.3.3
	- kleeslabs 12.3.0
	- krypton 0.2.1
	   \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- lambdynlights 2.2.0+1.19.2
	   |-- pride 1.1.2+1.19
	   \-- spruceui 4.1.0+1.19.2
	- lazydfu 0.1.3
	- lightoverlay 7.0.0
	- lithium 0.11.1
	- lootr 0.4.25.64
	- mavapi 1.0.1
	- mavm 1.2.0
	- mcwbridges 2.0.7
	- mcwdoors 1.0.8
	- mcwfences 1.0.7
	- mcwpaintings 1.0.4
	- mcwpaths 1.0.2
	- mcwroofs 2.2.3
	- medievalweapons 1.4.5
	   \-- reach-entity-attributes 2.3.0
	- memoryleakfix 1.0.0
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- midnightlib 1.0.0
	- minecarttweaks 1.7
	- minecraft 1.19.2
	- mixin-conflict-helper 1.2.0
	- mo_glass 1.6.1-MC1.19.2
	- modmenu 4.2.0-beta.2
	- modmenu-badges-lib 2023.4.1
	- moonlight 1.19.2-2.2.34
	- morevillagers 4.0.2
	- mousetweaks 2.22
	- naturescompass 1.19.2-2.1.0-fabric
	- notenoughanimations 1.6.2
	- numismatic-overhaul 0.2.8+1.19
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- stacc 1.3.3
	- one-time-overrides 1.0.1
	   \-- io_github_microutils_kotlin-logging-jvm 2.1.23
	- onsoulfire 1.19-2
	- optigui 2.1.0-beta.2
	   |-- optiglue 2.1.0-beta.2-mc.1.19
	   |-- org_apache_commons_commons-text 1.10.0
	   \-- org_ini4j_ini4j 0.5.4
	- owo 0.9.3+1.19
	- paintings 10.2.4.0
	- particlerain 2.0.0
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- phosphor 0.8.1
	- pickablevillagers 1.3.4+1.19.2
	- pickupnotifier 4.2.4
	- pigpen 11.1.2
	- plushies 1.2
	- polymorph 0.46.1+1.19.2
	- portfolio 1.19.2-1.2.0-fabric
	- puzzleslib 4.4.0
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- rainbegoneritual 3.0
	- randomsheepcolours 3.1
	- redstonepen 1.2.18
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- rightclickharvest 3.2.0+1.19.x
	- roughlyenoughitems 9.1.595
	   \-- error_notifier 1.0.9
	- roughlyenoughprofessions 1.1.4
	- roughlyenoughresources 2.6.0
	- rpgstats 4.5.0+1.19.2
	   |-- autoconfig1u 3.4.0
	   |-- libgui 6.0.0+1.19
	   |    |-- jankson 4.1.1+j1.2.1
	   |    \-- libninepatch 1.1.0
	   \-- server_translations_api 1.4.14+1.19-rc2
	        \-- packet_tweaker 0.3.0+1.18.2
	- satin 1.9.0
	- simplehats 1.19.2-0.1.6
	- skinlayers 1.5.2-mc1.19.1
	- smoothboot 1.19-1.7.1
	- snowrealmagic 5.1.1
	- sodium 0.4.4+build.18
	   \-- org_joml_joml 1.10.4
	- sodium-extra 0.4.16+mc1.19.2-build.90
	   \-- caffeineconfig 1.0.0+1.17
	- soulsweapons 0.9.9.3
	- spark 1.10.37
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- starterkit 5.2
	- strawgolem 2.0.0-beta.5
	- strawstatues 4.0.10
	- styled-nicknames 1.1.2+1.19
	   |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   |-- placeholder-api 2.0.0-beta.3+1.19
	   \-- player-data-api 0.1.0+1.18
	- terrablender 2.0.1.136
	- thonkutil 2.15.4+1.19
	   |-- thonkutil-base 1.13.2+4a8c408a57
	   |-- thonkutil-capes-v1 1.4.2+3eb2749857
	   |-- thonkutil-coords-v1 1.1.2+8ff533c957
	   |-- thonkutil-customization-v1 1.1.2+8ff533c957
	   |-- thonkutil-legacy 1.1.2+5d4263f557
	   |-- thonkutil-modchecker-v1 1.1.3+bd4b387957
	   |-- thonkutil-potions-v0 1.5.2+8ff533c957
	   |-- thonkutil-titlescreen-v1 1.2.2+8ff533c957
	   \-- thonkutil-trades-v1 1.2.2+8ff533c957
	- thorium 1.3.2
	- toms_storage 1.5.6
	- transparent 5.1.2
	- transportables 1.2.1
	- trashslot 12.0.2
	- trinkets 3.4.2
	- twigs 3.0.0
	- universalbonemeal 4.2.0
	- villagernames 4.5.1
	   |-- cardinal-components-base 5.0.2
	   \-- cardinal-components-level 5.0.2
	- visualworkbench 4.2.4
	- voidtotem 2.1.0
	- voidz 1.0.9
	- windchimes 1.2.1
	- wmitaf 3.1.1
	- worldtime 1.19.1-fabric0.58.5-1.3.1
	   |-- crowdin-translate 1.4+1.19
	   \-- gbfabrictools 1.3.4+1.19
	- yet-another-config-lib 2.2.0-for-1.19.2
	- yigd 1.4.9
	- z_mcwfencesbyg 1.19.2-1.0
	- zoomify 2.9.0
	   |-- dev_isxander_settxi_settxi-core 2.10.5
	   |-- dev_isxander_settxi_settxi-gui 2.10.5
	   |-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.5
	   \-- settxi-gui-yacl 2.10.5
```

**Comment by deli73** [comment]
according to the discord, this is an issue on 1.19+ versions due to registry changes. from the looks of it, this isn't getting fixed.

**Comment by notIkibo** [comment]
Crazy, that's really sad.
