### ISSUE TITLE
[Bug] 1.19.4 - Game crashing in the End

### ISSUE THREAD

**Issue by sinatomica** [quiqueck/BetterEnd#220]
### What happened?

After killing the dragon and entering the outer end islands portal, I load in perfectly fine but as I approach any terrain it becomes almost invisible and I crash. Sorry if I have missed anything or I have done stupid, just new to modding Minecraft.
![2023-06-12_20 11 27](https://github.com/quiqueck/BetterEnd/assets/136377741/6263a2e5-1872-4255-9439-14cd1caf16aa)

Edit: After disabling the Repurposed Structure mod, the game no longer crashes  but the terrain is still invisible.

### BetterEnd

3.2.1

### BCLib

2.3.2

### Fabric API

0.83.0

### Fabric Loader

0.11.2

### Minecraft

1.19.4

### Relevant log output

```shell
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-06-12 19:41:38
Description: Unexpected error

java.util.concurrent.CompletionException: net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:47)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:334)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:312)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:191)
	at net.minecraft.class_761.method_3273(class_761.java:12493)
	at net.minecraft.class_761.method_22710(class_761.java:1245)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:78)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$bka000$indium$onRenderBlock(ChunkRenderRebuildTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:104)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:286)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:328)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 64
	at me.jellysquid.mods.sodium.client.world.WorldSlice.getBlockState(WorldSlice.java:228)
	at me.jellysquid.mods.sodium.client.world.WorldSlice.method_8320(WorldSlice.java:220)
	at net.minecraft.class_2248.method_9607(class_2248.java:257)
	at me.pepperbell.continuity.client.model.CullingCache.shouldCull(CullingCache.java:20)
	at me.pepperbell.continuity.client.model.CullingCache.shouldCull(CullingCache.java:36)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.transform(CTMBakedModel.java:97)
	at link.infra.indium.renderer.render.AbstractRenderContext.lambda$new$1(AbstractRenderContext.java:32)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:41)
	at link.infra.indium.renderer.render.BaseQuadRenderer.renderQuad(BaseQuadRenderer.java:53)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.renderQuad(BaseFallbackConsumer.java:108)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:98)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:63)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:46)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:63)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:73)
	... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:47)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:334)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:312)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:191)
	at net.minecraft.class_761.method_3273(class_761.java:12493)
	at net.minecraft.class_761.method_22710(class_761.java:1245)
	at net.minecraft.class_757.method_3188(class_757.java:1100)

-- Affected level --
Details:
	All players: 1 total; [class_746['s_a_mh'/452, l='ClientLevel', x=1009.11, y=65.79, z=-89.72]]
	Chunk stats: 1024, 714
	Level dimension: minecraft:the_end
	Level spawn location: World: (0,63,-32), Section: (at 0,15,0 in 0,3,-2; chunk contains blocks 0,0,-32 to 15,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 5767 game time, 5767 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Better+Endermen.zip, fabric, continuity:default, continuity:glass_pane_culling_fix, cullleaves:smartleaves, file/Assorted+Allays+-+V.2.0.zip, file/Better_Rabbits.zip, file/Brewing+Guide.zip, file/Enhanced+Frogs.zip, file/Remodeled-Fence-and-Gates1.1.zip, file/ShieldCorrections+[Colored].zip, file/Shiny's+Rats+v1.zip, file/Shrimp's+Distinct+Potions.zip, file/[1.19.4]GUIRevision_1.0.zip, file/[1.2]+Enhanced+Boss+Bars.zip, file/crops-3d.zip, file/STONEBORN+Gear-LOW_EYES-1.19.3+-+V2.1.zip, file/Creeper_Overhaul_RP_1.1.2.zip, essential

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 717832880 bytes (684 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30646.20
	Virtual memory used (MB): 22080.22
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 1302.55
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		acclaimed_origins: Acclaimed Origins 1.0.0
		bclib: BCLib 2.3.2
		betterend: Better End 3.2.1
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		continuity: Continuity 3.0.0-beta.2+1.19.3
		cullleaves: Cull Leaves 3.0.3
			midnightlib: MidnightLib 1.1.0
		elementa: Elementa 590
		enchanted-vertical-slabs: Enchanted Vertical Slabs 1.8.1
		entity_model_features: Entity Model Features 0.2.9
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		essential: Essential 12840+deploy-staging+ge98314a1d
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		fabric-api: Fabric API 0.83.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.27+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.28+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+10ce000ff4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.37+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.18+10ce000ff4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.30+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.9+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.47+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.57+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.12+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.2+10ce000ff4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.3+10ce000ff4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.48+10ce000ff4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.16+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+10ce000ff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.55+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.35+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.20+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.8+10ce000ff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.18+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.30+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.34+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.4+10ce000ff4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.42+10ce000ff4
			fabric-models-v0: Fabric Models (v0) 0.3.33+10ce000ff4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.4+10ce000ff4
			fabric-networking-v0: Fabric Networking (v0) 0.3.44+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.6+10ce000ff4
			fabric-particles-v1: Fabric Particles (v1) 1.0.26+10ce000ff4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.11+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.3+10ce000ff4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.3.1+10ce000ff4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+10ce000ff4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.41+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.31+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.24+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.44+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.4+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.5+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.48+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.23+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.1+10ce000ff4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.2.0+10ce000ff4
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
		fabricloader: Fabric Loader 0.14.21
		fabricskyboxes: FabricSkyBoxes 0.7.1+mc1.19.4
		forgeconfigapiport: Forge Config API Port 6.0.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		geckolib: Geckolib 4.2
			com_eliotlash_mclib_mclib: mclib 20
		handcrafted: Handcrafted 2.2.0
		indium: Indium 1.0.18+mc1.19.4
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.0+1.19.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 4.2.0+1.19.4
		minecraft: Minecraft 1.19.4
		org_jetbrains_annotations: annotations 13.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		origins: Origins 1.9.0
			apoli: Apoli 2.8.0
				additionalentityattributes: Additional Entity Attributes 1.2.2+1.19.4
				calio: Calio 1.10.0
				cloth-config: Cloth Config v10 10.0.96
					cloth-basic-math: cloth-basic-math 0.6.1
				playerabilitylib: Pal 1.7.0
			reach-entity-attributes: Reach Entity Attributes 2.3.2
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		regions_unexplored: Regions Unexplored 0.4.1+1.19.4
		repurposed_structures: Repurposed Structures 6.3.25+1.19.4-fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		resourcefullib: Resourceful Lib 1.3.6
			com_teamresourceful_yabn: yabn 1.0.3
		simplehats: SimpleHats 1.19.4-0.2.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		terrablender: TerraBlender 2.2.0.161
		trinkets: Trinkets 3.6.0
		universalcraft: UniversalCraft 270
		vigilance: Vigilance 284
		xaeroworldmap: Xaero's World Map 1.30.3
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.21-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Better+Endermen.zip (incompatible), fabric, continuity:default (incompatible), continuity:glass_pane_culling_fix (incompatible), cullleaves:smartleaves (incompatible), file/Assorted+Allays+-+V.2.0.zip, file/Better_Rabbits.zip (incompatible), file/Brewing+Guide.zip (incompatible), file/Enhanced+Frogs.zip (incompatible), file/Remodeled-Fence-and-Gates1.1.zip (incompatible), file/ShieldCorrections+[Colored].zip (incompatible), file/Shiny's+Rats+v1.zip (incompatible), file/Shrimp's+Distinct+Potions.zip, file/[1.19.4]GUIRevision_1.0.zip, file/[1.2]+Enhanced+Boss+Bars.zip, file/crops-3d.zip (incompatible), file/STONEBORN+Gear-LOW_EYES-1.19.3+-+V2.1.zip (incompatible), file/Creeper_Overhaul_RP_1.1.2.zip (incompatible)
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['s_a_mh'/452, l='ServerLevel[New World]', x=1009.11, y=65.79, z=-89.72]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

**Comment by quiqueck** [comment]
Could you try if disabling continuity helps.

**Comment by sinatomica** [comment]
> Could you try if disabling continuity helps.

Hi, this has fixed the issue. Thank you so much. :D
