### ISSUE TITLE
[Crash] Server Crash on start Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!

### ISSUE THREAD

**Issue by Drakune** [quiqueck/BetterEnd#242]
### What happened?

Server crashes on startup
[18:53:28] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-1.20.1.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:88) ~[better-end-4.0.5.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:88) ~[better-end-4.0.5.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more

### BetterEnd

4.0.5

### BCLib

3.0.9

### Fabric API

0.83.1

### Fabric Loader

0.14.21

### Minecraft

1.20.1

### Relevant log output

```shell
[18:53:10] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[18:53:10] [ForkJoinPool-1-worker-4/WARN]: The mod "wunderlib" contains invalid entries in its mod json:
- Unsupported root entry "modmenu" at line 26 column 12
[18:53:10] [ForkJoinPool-1-worker-3/WARN]: Mod letmedespawn uses the version fabric-1.20-1.1.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:53:10] [main/INFO]: Loading 108 mods:
	- ae2 15.0.2-alpha
	   \-- team_reborn_energy 3.0.0
	- ae2wtlib 15.0.1-beta
	- appleskin 2.5.0+mc1.20
	- architectury 9.0.8
	- bclib 3.0.9
	   \-- wunderlib 1.1.2
	- betterend 4.0.5
	- betternether 9.0.6
	- cloth-config 11.0.99
	   \-- cloth-basic-math 0.6.1
	- collective 6.61
	- connectedglass 1.1.6
	- connectivity 1.20.1-4.2
	- cristellib 1.1
	- dungeons_andtaverns_mr 1-v2.1.3
	- easyelytratakeoff 4.0
	- elytraslot 6.3.0+1.20.1
	- fabric-api 0.83.1+1.20.1
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b77
	   |-- fabric-command-api-v1 1.2.32+f71b366f77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-commands-v0 0.2.49+df3654b377
	   |-- fabric-containers-v0 0.1.61+df3654b377
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.1.11+b3afc78b77
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.26+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b77
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c677
	   |-- fabric-message-api-v1 5.1.6+b3afc78b77
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-networking-v0 0.3.48+df3654b377
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b77
	   |-- fabric-particles-v1 1.0.28+b3afc78b77
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b77
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b77
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
	   |-- fabric-rendering-v0 1.1.47+df3654b377
	   |-- fabric-rendering-v1 3.0.6+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d77
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b77
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
	- fabric-language-kotlin 1.9.5+kotlin.1.8.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- ferritecore 6.0.0
	- immersive_aircraft 0.5.1+1.20.1
	- inventorytotem 3.0
	- jade 11.1.3
	- jamlib 0.6.0+1.20
	- java 17
	- letmedespawn fabric-1.20-1.1.0
	- mcwbridges 2.1.0
	- mcwpaths 1.0.3
	- mcwroofs 2.2.4
	- minecraft 1.20.1
	- modernfix 5.0.4+mc1.20.1
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b77
	- mtr 1.20-3.2.2-hotfix-1
	- owo 0.11.0+1.20
	   \-- blue_endless_jankson 1.2.2
	- rightclickharvest 3.2.2+1.19.x-1.20.1-fabric
	- roughlyenoughitems 12.0.625
	   \-- error_notifier 1.0.9
	- smoothchunk 1.20.1-3.0
	- supermartijn642corelib 1.1.9
	- t_and_t 1.10.2
	- treeharvester 8.2
	- trinkets 3.7.0
	   |-- cardinal-components-base 5.2.0
	   \-- cardinal-components-entity 5.2.0
	- universal-graves 3.0.0-beta.2+1.20
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.1.1+1.20
	   |-- polymer-core 0.5.0+1.20
	   |    |-- polymer-networking 0.5.0+1.20
	   |    |    \-- polymer-common 0.5.0+1.20
	   |    |         \-- packet_tweaker 0.4.0+1.19.4
	   |    \-- polymer-registry-sync-manipulator 0.5.0+1.20
	   |-- polymer-resource-pack 0.5.0+1.20
	   |    \-- polymer-common 0.5.0+1.20
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- polymer-virtual-entity 0.5.0+1.20
	   |    \-- polymer-common 0.5.0+1.20
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- predicate-api 0.1.2+1.20
	   |-- server_translations_api 2.0.0+1.20
	   |    \-- packet_tweaker 0.4.0+1.19.4
	   \-- sgui 1.2.2+1.20
[18:53:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/minecraft/server_1_20/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[18:53:11] [main/INFO]: Compatibility level set to JAVA_11
[18:53:11] [main/INFO]: Compatibility level set to JAVA_17
[18:53:11] [main/WARN]: Reference map 'connectedglass.mixins.refmap.json' for connectedglass.mixins.json could not be read. If this is a development environment you can ignore this message
[18:53:11] [main/WARN]: Reference map 'cristellib-common-refmap.json' for cristellib-common.mixins.json could not be read. If this is a development environment you can ignore this message
[18:53:12] [main/INFO]: Loaded configuration file for ModernFix: 43 options available, 0 override(s) found
[18:53:12] [main/INFO]: Applying Nashorn fix
[18:53:12] [main/WARN]: Error loading class: net/minecraft/class_634 (java.lang.ClassNotFoundException: net/minecraft/class_634)
[18:53:12] [main/WARN]: @Mixin target net.minecraft.class_634 was not found modernfix-fabric.mixins.json:core.ClientPlayNetHandlerMixin from mod modernfix
[18:53:12] [main/WARN]: Error loading class: net/minecraft/class_1043 (java.lang.ClassNotFoundException: net/minecraft/class_1043)
[18:53:12] [main/WARN]: @Mixin target net.minecraft.class_1043 was not found modernfix-fabric.mixins.json:safety.DynamicTextureMixin from mod modernfix
[18:53:12] [main/WARN]: Error loading class: net/minecraft/class_340 (java.lang.ClassNotFoundException: net/minecraft/class_340)
[18:53:12] [main/WARN]: @Mixin target net.minecraft.class_340 was not found modernfix-fabric.mixins.json:feature.branding.GuiMixin from mod modernfix
[18:53:12] [main/WARN]: Error loading class: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage (java.lang.ClassNotFoundException: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage)
[18:53:13] [main/WARN]: Mixin 'block.packet.ChunkDeltaUpdateS2CPacketMixin' from 'polymer-core' was disabled by Connectivity Mod (connectivity). Reason: Compat. This might cause issues and isn't generally supported!
[18:53:24] [main/INFO]: Vanilla bootstrap took 9207 milliseconds
[18:53:24] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[18:53:24] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[18:53:24] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[18:53:24] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[18:53:24] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[18:53:24] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[18:53:24] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[18:53:24] [main/WARN]: [bclib] Recipe betternether:bone_block_bone_button only takes in a single item and should be shapeless
[18:53:25] [main/INFO]: [rightclickharvest] Initializing VersionUtils
[18:53:25] [main/INFO]: [rightclickharvest] VersionUtils initialized successfully
[18:53:25] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[18:53:25] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[18:53:25] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[18:53:25] [main/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[18:53:25] [main/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[18:53:25] [main/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[18:53:25] [main/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[18:53:25] [main/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[18:53:25] [main/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[18:53:26] [main/INFO]: [betternether] =^..^=    BetterNether for 1.19    =^..^=
[18:53:27] [main/INFO]: Loading Collective version 6.61.
[18:53:27] [main/INFO]: Connectivity initialized
[18:53:27] [main/INFO]: [jamlib] Mod initialized!
[18:53:27] [main/INFO]: Logging initialized @19787ms to mtr.libraries.org.eclipse.jetty.util.log.Slf4jLog
[18:53:28] [main/INFO]: Maybe we take a page out of the Wisp Forest handbook: When in doubt, steal glisco's code
[18:53:28] [main/INFO]: [jamlib] Registered config for rightclickharvest
[18:53:28] [main/INFO]: [rightclickharvest] Mod initialized!
[18:53:28] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[18:53:28] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[18:53:28] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[18:53:28] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[18:53:28] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[18:53:28] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[18:53:28] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[18:53:28] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[18:53:28] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[18:53:28] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[18:53:28] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[18:53:28] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items
[18:53:28] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-1.20.1.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:88) ~[better-end-4.0.5.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:88) ~[better-end-4.0.5.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
```

**Comment by quiqueck** [comment]
Thanks for the report. I will upload an updated Version (4.0.6) in a few moments
