### ISSUE TITLE
[Bug]: Fabric Loader 0.14.21 Error

### ISSUE THREAD

**Issue by i5exr** [quiqueck/BetterEnd#277]
### What happened?

It tells me that bclib requires 0.86.0 version of Fabric API or later which is missing even tho i have 0.86.0 installed, and tells me that i should remove better end from the mods folder

![Screenshot 2023-07-24 122821](https://github.com/quiqueck/BetterEnd/assets/139549220/333e4eae-c5c2-48c7-9838-2914c852d4d0)

### BetterEnd

4.0.9

### BCLib

3.0.12

### Fabric API

0.86.0

### Fabric Loader

0.14.21

### Minecraft

1.20.1

### Relevant log output

```shell
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'Better End' (betterend) 4.0.9 (C:\Users\Hp\AppData\Roaming\.minecraft\mods\better-end-4.0.9.jar).
	 - Replace mod 'BCLib' (bclib) 3.0.12 with any version that is compatible with:
		 - Other constraints that can''t be automatically determined
Unmet dependency listing:
	 - Mod 'BCLib' (bclib) 3.0.12 is incompatible with version 0.86 or later of mod 'Fabric API' (fabric-api), but a matching version is present: 0.86.0+1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by nvb-uy** [comment]
+1

https://github.com/quiqueck/BCLib/issues/120

**Comment by MSandro** [comment]
hope the issue will be solved soon.

**Comment by paulevsGitch** [comment]
You need to use Fabric API 0.85. BClib is not compatible with 0.86
