### ISSUE TITLE
[Bug] Crash When Editing Config

### ISSUE THREAD

**Issue by LordEnder86** [quiqueck/BetterEnd#281]
### What happened?

Editing anything at all in any of the config files causes a crash. Been scratching my monkey head for a couple days now trying to disable some of the blocks/tools and some of the infusion recipes. In this example the only thing I changed was disabling thallasium ore: 
"thallasium_ore [default: true]": false,

[latest.log](https://github.com/quiqueck/BetterEnd/files/12235350/latest.log)

When crashing, it does not generate a crash report, only the log file.

Seems possibly similar to this issue https://github.com/quiqueck/BetterEnd/issues/218 ?

I feel like I remember hearing that better end doesn't work on fabric .86, but I can't remember where I may have read that.

### BetterEnd

4.0.8

### BCLib

3.0.11

### Fabric API

0.86.1

### Fabric Loader

0.14.21

### Minecraft

1.20.1

### Relevant log output

```shell
[20:17:10] [Worker-Main-5/WARN]: Exception loading blockstate definition: 'betterend:blockstates/thallasium_ore.json' missing model for variant: 'betterend:thallasium_ore#'
[20:17:11] [Worker-Main-5/INFO]: Loaded 89497 unsupported models.
[20:17:11] [Worker-Main-5/INFO]: Constructing diagonal block models took 3 milliseconds
[20:17:11] [Worker-Main-5/INFO]: 0% Cache coverage
[20:17:11] [Worker-Main-5/INFO]: with 91521 Fallback models
[20:17:11] [Worker-Main-5/INFO]: and  63 Cached models
[20:17:11] [Render thread/WARN]: Shader color_convolve could not find uniform named InSize in the specified shader program.
[20:17:11] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=Block{minecraft:air}}]
	at net.minecraft.class_2370.method_40276(class_2370.java:364) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47491(class_7923.java:239) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47476(class_7923.java:223) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$bnl002$fabric-registry-sync-v0$onStart(class_310.java:13039) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
[20:17:11] [Render thread/INFO]: Stopping!
```

**Comment by arsnoctis** [comment]
Tweaking because I'm having this problem right now
