### ISSUE TITLE
[Bug] server crash

### ISSUE THREAD

**Issue by mindryder** [quiqueck/BetterEnd#284]
### What happened?

server crash 2 times

### BetterEnd

betterend-4.0.10 [1.20.1]

### BCLib

bclib-3.0.13

### Fabric API

fabric-api-0.86.1+1.20.1

### Fabric Loader

fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2

### Minecraft

1.20.1

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-08-07 17:44:45
Description: Feature placement

java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1994)
	at java.base/java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2173)
	at java.base/java.util.HashMap.putVal(HashMap.java:644)
	at java.base/java.util.HashMap.put(HashMap.java:618)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeight(MountainPiece.java:115)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeightClamp(MountainPiece.java:133)
	at org.betterx.betterend.world.structures.piece.CrystalMountainPiece.method_14931(CrystalMountainPiece.java:93)
	at net.minecraft.class_3449.method_14974(class_3449.java:100)
	at net.minecraft.class_2794.method_38265(class_2794.java:320)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:319)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at net.minecraft.class_2806.md14144f$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:1608)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1994)
	at java.base/java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2173)
	at java.base/java.util.HashMap.putVal(HashMap.java:644)
	at java.base/java.util.HashMap.put(HashMap.java:618)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeight(MountainPiece.java:115)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeightClamp(MountainPiece.java:133)
	at org.betterx.betterend.world.structures.piece.CrystalMountainPiece.method_14931(CrystalMountainPiece.java:93)
	at net.minecraft.class_3449.method_14974(class_3449.java:100)
	at net.minecraft.class_2794.method_38265(class_2794.java:320)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:319)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)

-- Feature --
Details:
	Description: ResourceKey[minecraft:worldgen/structure / betterend:mountain]
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:319)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at net.minecraft.class_2806.md14144f$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:1608)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

-- Generation --
Details:
	CenterX: 552
	CenterZ: -321
	Seed: -3390187638322884702
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:319)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at net.minecraft.class_2806.md14144f$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:1608)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

-- Affected level --
Details:
	All players: 1 total; [class_3222['quntumic'/166860, l='ServerLevel[world]', x=8627.63, y=63.25, z=-5191.53]]
	Chunk stats: 2600
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-36,69,-15), Section: (at 12,5,1 in -3,4,-1; chunk contains blocks -48,0,-16 to -33,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 28756919 game time, 520883 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 86696 (now: false), thunder time: 48436 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:900)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1623)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 20.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 19541562560 bytes (18636 MiB) / 25769803776 bytes (24576 MiB) up to 27917287424 bytes (26624 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: Common KVM processor
	Identifier: AuthenticAMD Family 15 Model 6 Stepping 1
	Microarchitecture: K8 / Hammer
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Базовый видеоадаптер (Майкрософт)
	Graphics card #0 vendor: (Стандартные мониторы) (0x1234)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x1111
	Graphics card #0 versionInfo: DriverVersion=10.0.19041.1
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: RAM
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 0.00
	Memory slot #1 type: RAM
	Virtual memory max (MB): 34815.46
	Virtual memory used (MB): 29202.25
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 130.45
	JVM Flags: 2 total; -Xms24G -Xmx26G
	Fabric Mods: 
		anticreeper: §3§lAntiCreeper 2.0
		antixray: AntiXray 1.3.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		appleskin: AppleSkin 2.5.0+mc1.20
		azurelib: AzureLib 1.0.20
			com_eliotlash_mclib_mclib: mclib 20
		badpackets: Bad Packets 0.4.1
		balm-fabric: Balm 7.0.7
		banhammer: BanHammer 0.7.0+1.20
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			org_postgresql_postgresql: postgresql 42.5.1
			sgui: sgui 1.2.2+1.20
		banners4bm: Banners4BM 1.0.2
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		betterend: Better End 4.0.10
		bluemap: BlueMap 3.16
		bluemap_custom_skin_server: BlueMap Custom Skin Server 2023.6.1
		bookshelf: Bookshelf 20.0.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.96
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.96
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.96
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.96
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.96
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.96
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.96
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.96
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.96
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.96
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.96
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.96
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.96
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.96
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.96
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.96
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.96
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.96
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.96
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.96
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cardinal-components: Cardinal Components API 5.2.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			cardinal-components-level: Cardinal Components API (world saves) 5.2.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.1
			cardinal-components-world: Cardinal Components API (worlds) 5.2.1
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20.1-0.3.9
		collective: Collective 6.65
		connectivity: Connectivity Mod 1.20.1-4.4
		ctov: ChoiceTheorem's Overhauled Village 3.3.3
		d4f: Discord4Fabric 1.10.5
			club_minnced_discord-webhooks: discord-webhooks 0.8.0
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
			com_squareup_okhttp3_okhttp: okhttp 3.13.0
			com_squareup_okio_okio: okio 1.17.2
			com_vdurmont_emoji-java: emoji-java 5.1.1
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
			net_dv8tion_jda: JDA 5.0.0-beta.12
			net_sf_trove4j_trove4j: trove4j 3.0.3
			org_apache_commons_commons-collections4: commons-collections4 4.4
			org_json_json: json 20160212
		darkwaters: Dark Waters 0.0.19
		ducky-updater-lib: Ducky Updater 2023.6.1
		easyauth: Easy Authentication Mod 3.0.19
			at_favre_lib_bcrypt: bcrypt 0.9.0
			at_favre_lib_bytes: bytes 1.5.0
			de_mkammerer_argon2-jvm: argon2-jvm 2.11
			de_mkammerer_argon2-jvm-nolibs: argon2-jvm-nolibs 2.11
			net_java_dev_jna_jna: jna 5.12.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_mongodb_bson: bson 4.7.2
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.7.2
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.7.2
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		emi: EMI 1.0.18+1.20.1+fabric
		emotecraft: Emotecraft 2.2.7-b.build.50
			player-animator: Player Animator 1.0.2-rc1+1.20
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fabrictailor: Fabric Tailor 2.1.2
		fallingtree: FallingTree 4.3.0
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		fastload: Fast Load 3.4.0
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.4.0
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.4.0
			fastload-1194-compat: Fastload 1.19.4 Compat 3.4.0
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.2
		ferritecore: FerriteCore 6.0.0
		firespreadtweaks: Fire Spread Tweaks 2.3
		forgeconfigapiport: Forge Config API Port 8.0.0
		geckolib: Geckolib 4.2.1
		genshinstrument: Genshin Instruments 3.1.2.2
		goml: Get Off My Lawn ReServed 1.9.0+1.20-rc1
			common-protection-api: Common Protection API 1.0.0
			playerabilitylib: Pal 1.8.0-patbox
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		guardiansgalore: GuardiansGalore 1.20.1-3.1
		healingcampfire: Healing Campfire 5.1
		holograms: Holograms (Legacy Edition) 1.5.2+1.20-legacy-edition
			hologram-api: Hologram API 0.2.4+1.20
		htm: Hey That's Mine 1.1.9
		huskhomes: HuskHomes 4.4.6-6455f15
			com_h2database_h2: h2 2.2.220
			com_mysql_mysql-connector-j: mysql-connector-j 8.1.0
			org_apache_commons_commons-pool2: commons-pool2 2.11.1
			org_mariadb_jdbc_mariadb-java-client: mariadb-java-client 3.1.4
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.42.0.0
			redis_clients_jedis: jedis 4.4.2
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		ironchest: Iron Chests 2.0.0
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 20
		journeymap: Journeymap 5.9.12
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		justmobheads: Just Mob Heads 7.3
		justplayerheads: Just Player Heads 3.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		leaky: leaky Mod 1.20.1-1.4
		letmedespawn: Let Me Despawn fabric-1.20-1.1.0
		lithium: Lithium 0.11.2
		luckperms: LuckPerms 5.4.98
		luckperms-placeholders: LuckPerms Placeholders 5.4-SNAPSHOT
		mapfrontiers: MapFrontiers 2.6.0
			commonnetworking: Common Network 1.0.1-1.20.1
		mcwbridges: Macaw's Bridges 2.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		memoryleakfix: Memory Leak Fix 1.1.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		minecraft: Minecraft 1.20.1
		minimotd-fabric: MiniMOTD 2.0.13
			adventure-platform-fabric: adventure-platform-fabric 5.10.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.14.0
				net_kyori_adventure-key: adventure-key 4.14.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.14.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.14.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.14.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.14.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.14.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.14.0
				net_kyori_ansi: ansi 1.0.1
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
		moremobvariants: More Mob Variants 1.2.2
		mr_ctov_farmersdelightcompat: CTOV - Farmer Delight Compat 2.0
		mr_double_doorsdp: Double Doors 1.1
		mythicmounts: Mythic Mounts 1.20.1-7.2
		patchouli: Patchouli 1.20.1-81-FABRIC
			fiber: fiber 0.23.0-2
		regions_unexplored: Regions Unexplored 0.4.1+1.20.1
		simplehats: SimpleHats 1.20.1-0.2.0
		sit: Sit! 1.0.2+1.20-1.20.1
		smartbrainlib: SmartBrainLib 1.11.1
		starterkit: Starter Kit 5.2
		styledchat: Styled Chat 2.2.2+1.20.1
			placeholder-api: Placeholder API 2.1.2+1.20.1
			player-data-api: Player Data API 0.2.2+1.19.3
		tab: TAB 4.0.3
		taterzens: Taterzens 1.11.6
			config2brigadier: Config to Brigadier 1.2.5
		terrablender: TerraBlender 3.0.0.169
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.2
		trinkets: Trinkets 3.7.1
		ubesdelight: Ube's Delight 0.1.3
		universal-graves: Universal Graves 3.0.0-beta.4+1.20.1
			polymer-core: Polymer (Core) 0.5.3+1.20.1
				polymer-networking: Polymer (Networking) 0.5.3+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.3+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.3+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.3+1.20.1
				polymer-common: Polymer (Common) 0.5.3+1.20.1
			predicate-api: Predicate API 0.1.2+1.20
		universal_shops: Universal Shops 1.3.2+1.20.1
			common-economy-api: Common Economy API 1.1.1
		uselessreptile: Useless Reptile 0.4.3-1.20.1
		vmp: Very Many Players 0.2.0+beta.7.100
		voicechat: Simple Voice Chat 1.20.1-2.4.16
		waystones: Waystones 14.0.1
		wildlife: Wildlife 1.19.2-2.2
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		wthit: wthit 8.3.0
		yawp: Yet Another World Protector 0.0.2.9-beta2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	Server Running: true
	Player Count: 3 / 666; [class_3222['MindRyder'/225, l='ServerLevel[world]', x=-487.85, y=64.00, z=206.46], class_3222['YvngDarling'/69005, l='ServerLevel[world]', x=-1536.39, y=-54.00, z=1567.67], class_3222['quntumic'/166860, l='ServerLevel[world]', x=8627.63, y=63.25, z=-5191.53]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by mindryder** [comment]
other crash  
[crash-2023-08-07_12.22.10-server.txt](https://github.com/quiqueck/BetterEnd/files/12281763/crash-2023-08-07_12.22.10-server.txt)

**Comment by purejosh** [comment]
When will this be fixed? It's been open for 8 months. Server crashes are serious, and should receive priority in the bugfixes. I just had a regression caused by this crash, and manually restoring player's items is tedious.

**Comment by s-liwka** [comment]
> When will this be fixed? It's been open for 8 months. Server crashes are serious, and should receive priority in the bugfixes. I just had a regression caused by this crash, and manually restoring player's items is tedious.

This is apparently related to C2ME, not BetterEnd

https://github.com/quiqueck/BetterEnd/issues/204

**Comment by purejosh** [comment]
> > When will this be fixed? It's been open for 8 months. Server crashes are serious, and should receive priority in the bugfixes. I just had a regression caused by this crash, and manually restoring player's items is tedious.
> 
> This is apparently related to C2ME, not BetterEnd
> 
> #204

And they're saying it's BE's issue, which after looking at their feature generation, makes sense. 

@quiqueck 
https://github.com/RelativityMC/C2ME-fabric/issues/236#issuecomment-1678710872

**Comment by purejosh** [comment]
I wish both devs would just get into a call and sort this out.

**Comment by s-liwka** [comment]
eh switching one option in the c2me config fixed it for me

**Comment by liangmoe** [comment]
Usually quiqueck will solve every issue as much as possible, you can see how the recent issue being closed, he just dont have free time currently, there is no way to give any pressure for him, we play mods for free and we have time to wait him come back

**Comment by AlienXtream** [comment]
still a thing. i assume its a race condition. couldn't a fallback be implemented to just use air? would rather that than a crash. maybe someone can/has made a PR?
