### ISSUE TITLE
[Bug] can't open patchouli book

### ISSUE THREAD

**Issue by Flanta** [quiqueck/BetterEnd#287]
### What happened?

the patchouli book(the end for dummies) isn't opening. you cant even put it in a lectern. the recipe isn't showing up in REI or the minecraft recipe book.

patchouli version: 1.20.1-81-fabric

### BetterEnd

4.0.10

### BCLib

3.0.13

### Fabric API

0.86.1+1.20.1

### Fabric Loader

0.14.22

### Minecraft

1.20.1

**Comment by Atmois** [comment]
Having the same issue, seems to be this causing it.

This seems to outline how to fix it:
https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120

```
[13:13:59] [Render thread/ERROR]: Failed to load book betterend:guidebook defined by mod betterend, skipping
java.lang.IllegalArgumentException: Book betterend:guidebook has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[transformed-mod-patchouli.i0:0/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[transformed-mod-patchouli.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55) ~[quilt-loader-0.19.3.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by mindryder** [comment]
[15:45:59] [main/ERROR]: Failed to load book betterend:guidebook defined by mod betterend, skipping
java.lang.IllegalArgumentException: Book betterend:guidebook has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2.jar:0.11.2]

**Comment by quiqueck** [comment]
Just merged the PR by @noah1510 (thanks for helping!), Should be fixed with the next release.
