### ISSUE TITLE
[Bug] Crashes while putting down Eternal Crystals

### ISSUE THREAD

**Issue by 1356RYAN** [quiqueck/BetterEnd#293]
### What happened?

We tried to make a portal using the eternal crystals. When put on the pedestal, it crashes the server.

### BetterEnd

 4.0.10

### BCLib

 3.0.13

### Fabric API

0.87.0

### Fabric Loader

0.14.22

### Minecraft

1.20.1

### Relevant log output

```shell
Time: 2023-08-20 16:46:44
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "$$0" is null
	at net.minecraft.class_2512.method_10692(class_2512.java:207)
	at org.betterx.betterend.rituals.EternalRitual.toTag(EternalRitual.java:491)
	at org.betterx.betterend.blocks.entities.EternalPedestalEntity.method_11007(EternalPedestalEntity.java:41)
	at net.minecraft.class_2586.method_38244(class_2586.java:84)
	at org.betterx.betterend.blocks.entities.PedestalBlockEntity.method_16887(PedestalBlockEntity.java:123)
	at net.minecraft.class_2622.method_39026(class_2622.java:21)
	at net.minecraft.class_2622.method_38585(class_2622.java:25)
	at org.betterx.betterend.blocks.entities.PedestalBlockEntity.getUpdatePacket(PedestalBlockEntity.java:118)
	at org.betterx.betterend.blocks.entities.PedestalBlockEntity.method_38235(PedestalBlockEntity.java:17)
	at net.minecraft.class_3193.method_14009(class_3193.java:305)
	at net.minecraft.class_3193.method_30311(class_3193.java:298)
	at net.minecraft.class_3193.method_14006(class_3193.java:284)
	at net.minecraft.class_3215.method_38784(class_3215.java:393)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.class_3215.method_14161(class_3215.java:393)
	at net.minecraft.class_3215.method_12127(class_3215.java:326)
	at net.minecraft.class_3218.method_18765(class_3218.java:333)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2512.method_10692(class_2512.java:207)
	at org.betterx.betterend.rituals.EternalRitual.toTag(EternalRitual.java:491)
	at org.betterx.betterend.blocks.entities.EternalPedestalEntity.method_11007(EternalPedestalEntity.java:41)
	at net.minecraft.class_2586.method_38244(class_2586.java:84)
	at org.betterx.betterend.blocks.entities.PedestalBlockEntity.method_16887(PedestalBlockEntity.java:123)
	at net.minecraft.class_2622.method_39026(class_2622.java:21)
	at net.minecraft.class_2622.method_38585(class_2622.java:25)
	at org.betterx.betterend.blocks.entities.PedestalBlockEntity.getUpdatePacket(PedestalBlockEntity.java:118)
	at org.betterx.betterend.blocks.entities.PedestalBlockEntity.method_38235(PedestalBlockEntity.java:17)
	at net.minecraft.class_3193.method_14009(class_3193.java:305)
	at net.minecraft.class_3193.method_30311(class_3193.java:298)
	at net.minecraft.class_3193.method_14006(class_3193.java:284)
	at net.minecraft.class_3215.method_38784(class_3215.java:393)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.class_3215.method_14161(class_3215.java:393)
	at net.minecraft.class_3215.method_12127(class_3215.java:326)
	at net.minecraft.class_3218.method_18765(class_3218.java:333)
-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 562223296 bytes (536 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.89
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2544
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3699
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32657.09
	Virtual memory used (MB): 24293.56
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 1333.26
	JVM Flags: 1 total; -Xmx4G
	Fabric Mods: 
		abverticaledition: Additional Blocks: Vertical Edition 1.0.3-b
		ae2: Applied Energistics 2 15.0.7-beta
			team_reborn_energy: Energy 3.0.0
		ae2wtlib: AE2WTLib 15.0.1-beta
		anvil_fix: AnvilFix development+20230626064221-1.20.1
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		balm-fabric: Balm 7.0.7
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		betterend: Better End 4.0.10
		bookshelf: Bookshelf 20.0.2
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.2-1.20
			maelstrom_library: Maelstrom Library 1.6-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 6.65
		companion: Companion 5.0.2
		craterlib: CraterLib 1.0.2
		darkpaintings: DarkPaintings 17.0.1
		debugify: Debugify 1.20.1+2.0
		doubledoors: Double Doors 5.0
		dramaticdoors: Dramatic Doors (Fabric) 1.20.1-2.0.1
		elytratrims: Elytra Trims 1.2.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			conditional-mixin: conditional mixin 0.3.2
		expandeddelight: Expanded Delight 0.3.0.2
		extraorigins: Extra Origins 1.20-1
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.22
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		ferritecore: FerriteCore 6.0.0
		fishofthieves: Fish of Thieves 3.0.2
		flan: Flan 1.20.1-1.8.7
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		geckolib: Geckolib 4.2.1
			com_eliotlash_mclib_mclib: mclib 20
		getittogetherdrops: Get It Together, Drops! fabric-1.20-1.3.1
		iammusicplayer: Iam Music Player 3.22.0-alpha.1
		image2map: Image2Map 0.4.2+1.20
			map-canvas-api: Map Canvas API 0.2.2+1.19.4
			sgui: sgui 1.2.2+1.20
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		jade: Jade 11.5.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		letmedespawn: Let Me Despawn fabric-1.20-1.1.0
		lithium: Lithium 0.11.2
		memoryleakfix: Memory Leak Fix 1.1.1
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		moborigins: Mob Origins 1.11.1
		moonlight: Moonlight 1.20-2.8.2
		mousewheelie: Mouse Wheelie 1.12.2+mc1.20.1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		origins-classes: Origins: Classes 1.7.0
		otyacraftengine: Otyacraft Engine 3.7.0-alpha.2
		pehkui: Pehkui 3.7.8+1.14.4-1.20.1
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		quartzelv: Quartz Elevator 2.2.5+1.20
		repurposed_structures: Repurposed Structures 7.0.0+1.20-fabric
		roughlyenoughitems: Roughly Enough Items 12.0.645
			error_notifier: Error Notifier 1.0.9
		sdlink: Simple Discord Link 2.2.2
		seasons: Fabric Seasons 2.3+1.20
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		simple-rpc: Simple RPC 3.2.2
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 5.0.0
		sit: Sit 1.20-24
		spark: spark 1.10.42
		starlight: Starlight 1.1.2+fabric.dbc156f
		supplementaries: Supplementaries 1.20-2.5.25
		textile_backup: Textile Backup 3.1.0-1.20
			com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
			org_apache_commons_commons-compress: commons-compress 1.22
			org_tukaani_xz: xz 1.9
		touhouorigins: Touhou Origins 1.0.0
			apugli: Apugli 2.4.4+1.20.1-fabric
		trashslot: TrashSlot 15.0.0
		trinkets: Trinkets 3.7.1
		ultris_mr: Ultris: Boss Expansion 5.6.9b
		universal_shops: Universal Shops 1.3.2+1.20.1
			common-economy-api: Common Economy API 1.1.1
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.1+1.20
			polymer-core: Polymer (Core) 0.5.3+1.20.1
				polymer-networking: Polymer (Networking) 0.5.3+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.3+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.3+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.3+1.20.1
				polymer-common: Polymer (Common) 0.5.3+1.20.1
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		vanityslots: Vanity Slots 1.2.9
		vcinteraction: Voice Chat Interaction 1.20.1-1.0.3
		voicechat: Simple Voice Chat 1.20.1-2.4.19
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		wwoo: William Wythers' Overhauled Overworld 3.2.0-beta
		xaerominimap: Xaero's Minimap 23.6.2
		xaeroworldmap: Xaero's World Map 1.33.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
```

**Comment by AlicoCat** [comment]
i'm also having this issue, commenting in case someone replies with a fix, because i really dont want to take betterend out of my world, its too fun

**Comment by AlicoCat** [comment]
this only seems to be happening with the eternal pedestal, which is also the only one that changes visually when the crystal is put on it, probably something to do with that but im not smart enough to know why

**Comment by BreadsticksMax** [comment]
> this only seems to be happening with the eternal pedestal, which is also the only one that changes visually when the crystal is put on it, probably something to do with that but im not smart enough to know why

Probably a rendering issue with one of the other mods, I'm having the same thing rn. Did you end up finding a fix?

**Comment by ImJVNE** [comment]
I have the exact same problem. it really sucks and I have not a singular clue how to fix that issue.

**Comment by masuteri** [comment]
I have a similar issue, but the server crashes because of watchdog. And it's also a server so it can't be a rendering issue

**Comment by masuteri** [comment]
For some reason it just takes a very very long time to make the portal, all you can do is wait apparently.
