### ISSUE TITLE
My set of mods worked without this mod

### ISSUE THREAD

**Issue by Feliks-WR** [quiqueck/BetterEnd#305]
### What happened?

I removed it, so it worked!
Check log:

	[15:50:51] [Render thread/ERROR]:
 Failed to load book betterend:guidebook defined by mod betterend, skipping
java.lang.IllegalArgumentException: Book betterend:guidebook has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[transformed-mod-patchouli.i0:0/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[transformed-mod-patchouli.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55) ~[quilt-loader-0.20.2.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[quilt-loader-0.20.2-1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.2.jar:?]
[15:50:51] [Render thread/ERROR]:
 Failed to load book betternether:betternether_book defined by mod betternether, skipping
java.lang.IllegalArgumentException: Book betternether:betternether_book has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[transformed-mod-patchouli.i0:0/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[transformed-mod-patchouli.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55) ~[quilt-loader-0.20.2.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[quilt-loader-0.20.2-1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.2.jar:?]
[15:51:24] [CraftPresence/ERROR]:
 Unable to get "atlauncher" pack data (ignore if not using a "atlauncher" pack)
[15:51:24] [CraftPresence/ERROR]:
 Unable to get "curse" pack data (ignore if not using a "curse" pack)
[15:51:24] [CraftPresence/ERROR]:
 Unable to get "mcupdater" pack data (ignore if not using a "mcupdater" pack)
[15:51:25] [CraftPresence/ERROR]:
 Asset name "mymods_1_" does not exist, attempting to use an alternative icon "modrinth"...

### BetterEnd

4.0.10

### BCLib

3.0.13

### Fabric API

QFAPI 7.3.0+0.89.0-1.20.1

### Fabric Loader

quilt 0.20.2

### Minecraft

1.20.1

### Relevant log output

```shell
[15:50:51] [Render thread/ERROR]:
 Failed to load book betterend:guidebook defined by mod betterend, skipping
java.lang.IllegalArgumentException: Book betterend:guidebook has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[transformed-mod-patchouli.i0:0/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[transformed-mod-patchouli.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55) ~[quilt-loader-0.20.2.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[quilt-loader-0.20.2-1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.2.jar:?]
[15:50:51] [Render thread/ERROR]:
 Failed to load book betternether:betternether_book defined by mod betternether, skipping
java.lang.IllegalArgumentException: Book betternether:betternether_book has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[transformed-mod-patchouli.i0:0/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[transformed-mod-patchouli.i0:0/:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[transformed-mod-patchouli.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55) ~[quilt-loader-0.20.2.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[quilt-loader-0.20.2-1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.2.jar:?]
[15:51:24] [CraftPresence/ERROR]:
 Unable to get "atlauncher" pack data (ignore if not using a "atlauncher" pack)
[15:51:24] [CraftPresence/ERROR]:
 Unable to get "curse" pack data (ignore if not using a "curse" pack)
[15:51:24] [CraftPresence/ERROR]:
 Unable to get "mcupdater" pack data (ignore if not using a "mcupdater" pack)
[15:51:25] [CraftPresence/ERROR]:
 Asset name "mymods_1_" does not exist, attempting to use an alternative icon "modrinth"...
```

### Other Mods

```shell
Better Nether
Optimization mods (Sodium, Starlight etc)
MANY Others
```

**Comment by Feliks-WR** [comment]
[2023-09-25-3.log](https://github.com/quiqueck/BetterEnd/files/12714363/2023-09-25-3.log)
