### ISSUE TITLE
[Bug] Server Crashes With No Log [1.20.1]

### ISSUE THREAD

**Issue by Kunabee** [quiqueck/BetterEnd#322]
I've been working on a small modpack for myself and my friends, and of course that means setting up a server so we can play.

Three months ago, with a previous version of mods, Fabric, etc, the server popped up fine (but suffered from other crashes and issues that the client ALSO suffered from). Now, the server won't generate at all - it doesn't even generate a crashlog, though a third-party program will make a log of the console for me.

In this crashlog, it says there's no such thing as CLIENT_CONFIG.

The weird thing is, when I generate a world and play around in it on the client, it works fine. It's ONLY when I make a server that this issue comes up. It's not properly generating the configs at all, either, and copying/pasting the configs from the client to the server doesn't work.

I've tried different versions (including the alpha version of BetterEnd for 1.20.1), different Fabric versions (obviously, if you go too far back with Fabric, that doesn't work either), running it with JUST BetterEnd and BCLib, etc... the issue is the same.

I'm at the end of my rope. I have no idea what's going on or how to fix this. It worked before on an earlier version???? I just.

help.

### BetterEnd

4.0.10

### BCLib

3.0.13

### Fabric API

0.91.0

### Fabric Loader

0.15.1

### Minecraft

1.20.1

### Relevant log output

```shell
[02:48:24] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.1
[02:48:24] [main/INFO]: Loading 48 mods:
	- bclib 3.0.13
	   \-- wunderlib 1.1.5
	- betterend 4.0.5
	- betternether 9.0.9
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- java 17
	- minecraft 1.20.1
	- wunderreich 6.0.4
[02:48:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Users/Owner/Documents/my%20games/Downloaded%20Games/Minecraft/server%20stuff/MCSS%20-%20MC%20ServerSoft/servers/test/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[02:48:24] [main/INFO]: Compatibility level set to JAVA_17
[02:48:26] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[02:48:43] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[02:48:43] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[02:48:43] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[02:48:43] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[02:48:43] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[02:48:43] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[02:48:43] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[02:48:44] [main/WARN]: [bclib] Recipe betternether:bone_block_bone_button only takes in a single item and should be shapeless
[02:48:45] [main/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[02:48:45] [main/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[02:48:45] [main/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[02:48:45] [main/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[02:48:45] [main/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[02:48:45] [main/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[02:48:45] [main/INFO]: [betternether] =^..^=    BetterNether for 1.20    =^..^=
[02:48:46] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bclib'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.1.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.2]
	Suppressed: java.lang.NoSuchFieldError: CLENT_CONFIG
		at org.betterx.betterend.config.Configs.<clinit>(Configs.java:22) ~[better-end-4.0.5.jar:?]
		at org.betterx.betterend.registry.EndBlocks.<clinit>(EndBlocks.java:29) ~[better-end-4.0.5.jar:?]
		at org.betterx.betterend.registry.EndBlockEntities.<clinit>(EndBlockEntities.java:17) ~[better-end-4.0.5.jar:?]
		at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:46) ~[better-end-4.0.5.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.1.jar:?]
		at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.2]
	Suppressed: java.lang.NoSuchFieldError: texture
		at de.ambertation.wunderreich.utils.WunderKisteDomain.<init>(WunderKisteDomain.java:75) ~[wunderreich-6.0.4.jar:?]
		at de.ambertation.wunderreich.utils.WunderKisteDomain.<clinit>(WunderKisteDomain.java:27) ~[wunderreich-6.0.4.jar:?]
		at de.ambertation.wunderreich.blocks.WunderKisteBlock.<clinit>(WunderKisteBlock.java:86) ~[wunderreich-6.0.4.jar:?]
		at de.ambertation.wunderreich.registries.WunderreichBlocks.lambda$static$0(WunderreichBlocks.java:30) ~[wunderreich-6.0.4.jar:?]
		at de.ambertation.wunderreich.registries.WunderreichBlocks.registerBlock(WunderreichBlocks.java:71) ~[wunderreich-6.0.4.jar:?]
		at de.ambertation.wunderreich.registries.WunderreichBlocks.<clinit>(WunderreichBlocks.java:27) ~[wunderreich-6.0.4.jar:?]
		at de.ambertation.wunderreich.registries.WunderreichBlockEntities.<clinit>(WunderreichBlockEntities.java:25) ~[wunderreich-6.0.4.jar:?]
		at de.ambertation.wunderreich.Wunderreich.onInitialize(Wunderreich.java:56) ~[wunderreich-6.0.4.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.1.jar:?]
		at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.2]
Caused by: java.lang.NoSuchFieldError: CLIENT_CONFIG
	at org.betterx.bclib.registry.PresetsRegistry.register(PresetsRegistry.java:17) ~[bclib-3.0.13.jar:?]
	at org.betterx.bclib.BCLib.onInitialize(BCLib.java:73) ~[bclib-3.0.13.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.1.jar:?]
	... 7 more
```

### Other Mods

```shell
Better Nether 9.0.9
Wunderreich 6.0.4

The full modpack has a lot more, but it's crashing with just these. It even crashes solely as BCLib and BetterEnd
```

**Comment by Skullians** [comment]
First of all
it is crashing with a log xd
Here is your solution:
Downgrade Fabric Loader (NOT Fabric API) to 0.14.25.
duplicate of https://github.com/quiqueck/BCLib/issues/136

**Comment by Skullians** [comment]
this should have been made in the bclib discord as it clearly states the crash is to do with bclib :)

**Comment by Kunabee** [comment]
No crash report, is what I meant, thank you. I'll close this and use the solution, I appreciate it.

**Comment by Skullians** [comment]
oh sorry, glad to help though
