### ISSUE TITLE
[Bug] Crash while exploring and rendering

### ISSUE THREAD

**Issue by C41nn** [quiqueck/BetterEnd#326]
### What happened?

Server crashed while generating the End city. The save didnt corrupt and after restarting server everything rendered normaly?

### BetterEnd

4.0.10

### BCLib

3.0.13

### Fabric API

0.88.1+1.20.1

### Fabric Loader

0.14.25

### Minecraft

1.20.1

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2023-12-27 02:19:48
Description: Ticking block entity

java.lang.IllegalArgumentException: Transfer variant may not be blank.
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:39)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:58)
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.extract(SingleStackStorage.java:136)
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.extract(SingleStackStorage.java:42)
	at io.github.fabricators_of_create.porting_lib.transfer.TransferUtil.clearStorage(TransferUtil.java:343)
	at com.simibubi.create.content.contraptions.MountedStorageManager.clear(MountedStorageManager.java:189)
	at com.simibubi.create.content.contraptions.Contraption.addBlocksToWorld(Contraption.java:1132)
	at com.simibubi.create.content.contraptions.AbstractContraptionEntity.disassemble(AbstractContraptionEntity.java:667)
	at com.simibubi.create.content.contraptions.OrientedContraptionEntity.method_5848(OrientedContraptionEntity.java:156)
	at net.minecraft.class_1297.method_5772(class_1297.java:2138)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.disassembleCart(CartAssemblerBlockEntity.java:223)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.disassemble(CartAssemblerBlockEntity.java:193)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.tryAssemble(CartAssemblerBlockEntity.java:86)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.tick(CartAssemblerBlockEntity.java:65)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:39)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:58)
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.extract(SingleStackStorage.java:136)
	at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.extract(SingleStackStorage.java:42)
	at io.github.fabricators_of_create.porting_lib.transfer.TransferUtil.clearStorage(TransferUtil.java:343)
	at com.simibubi.create.content.contraptions.MountedStorageManager.clear(MountedStorageManager.java:189)
	at com.simibubi.create.content.contraptions.Contraption.addBlocksToWorld(Contraption.java:1132)
	at com.simibubi.create.content.contraptions.AbstractContraptionEntity.disassemble(AbstractContraptionEntity.java:667)
	at com.simibubi.create.content.contraptions.OrientedContraptionEntity.method_5848(OrientedContraptionEntity.java:156)
	at net.minecraft.class_1297.method_5772(class_1297.java:2138)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.disassembleCart(CartAssemblerBlockEntity.java:223)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.disassemble(CartAssemblerBlockEntity.java:193)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.tryAssemble(CartAssemblerBlockEntity.java:86)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.tick(CartAssemblerBlockEntity.java:65)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: create:cart_assembler // com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity
	Block: Block{create:cart_assembler}[backwards=false,powered=false,rail_type=regular,shape=east_west,waterlogged=false]
	Block location: World: (751,16,2), Section: (at 15,0,2 in 46,1,0; chunk contains blocks 736,0,0 to 751,255,15), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Block: Block{create:cart_assembler}[backwards=false,powered=false,rail_type=regular,shape=east_west,waterlogged=false]
	Block location: World: (751,16,2), Section: (at 15,0,2 in 46,1,0; chunk contains blocks 736,0,0 to 751,255,15), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

-- Affected level --
Details:
	All players: 4 total; [class_3222['edein_'/298065, l='ServerLevel[e11]', x=749.99, y=16.00, z=4.94], class_3222['mariusz9q'/300172, l='ServerLevel[e11]', x=748.38, y=18.06, z=5.60], class_3222['wicia123'/297814, l='ServerLevel[e11]', x=738.11, y=16.00, z=1.71], class_3222['mmisia'/323251, l='ServerLevel[e11]', x=746.82, y=17.44, z=3.87]]
	Chunk stats: 2209
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (0,111,0), Section: (at 0,15,0 in 0,6,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8318899 game time, 8935447 day time
	Level name: e11
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 49990 (now: false), thunder time: 125526 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.10.0-26-cloud-amd64
	Java Version: 17.0.9, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Debian
	Memory: 2567006200 bytes (2448 MiB) / 6249512960 bytes (5960 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7B13
	Identifier: AuthenticAMD Family 25 Model 1 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Virtio SCSI
	Graphics card #0 vendor: Red Hat, Inc. (0x1af4)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x1004
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8003.63
	Virtual memory used (MB): 8104.91
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xmx6144M -Xms1024M
	Fabric Mods: 
		ae2: Applied Energistics 2 15.0.15
			team_reborn_energy: Energy 3.0.0
		aquamirae: Aquamirae 6
		architectury: Architectury 9.1.12
		badpackets: Bad Packets 0.4.3
		balm-fabric: Balm 7.2.1
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		bettercombat: Better Combat 1.8.3+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0
		betterend: Better End 4.0.10
		betternether: Better Nether 9.0.9
		blossom-homes: BlossomHomes 2.2.1+1.20
		blossom-lib: BlossomLib 2.5.4+1.20
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		blossom-pvp: BlossomPVP 2.0.1+1.20
		blossom-tpa: BlossomTpa 2.2.1+1.20
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.4-1.20.1
			maelstrom_library: Maelstrom Library 1.6.1-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.0
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.0
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.0
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.0
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.0
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.0
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.0
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.0
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.0
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.0
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.0
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.0
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.0
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.0
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.0
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		easyauth: Easy Authentication Mod 3.0.19
			at_favre_lib_bcrypt: bcrypt 0.9.0
			at_favre_lib_bytes: bytes 1.5.0
			com_mysql_mysql-connector-j: mysql-connector-j 8.0.33
			de_mkammerer_argon2-jvm: argon2-jvm 2.11
			de_mkammerer_argon2-jvm-nolibs: argon2-jvm-nolibs 2.11
			net_java_dev_jna_jna: jna 5.12.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_mongodb_bson: bson 4.7.2
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.7.2
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.7.2
		expandeddelight: Expanded Delight 0.3.0.2
		fabric-api: Fabric API 0.88.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.16+kotlin.1.9.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.14.25
		fabrictailor: Fabric Tailor 2.1.2
			config2brigadier: Config to Brigadier 1.2.3
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		ferritecore: FerriteCore 6.0.0
		geckolib: Geckolib 4.2.3
			com_eliotlash_mclib_mclib: mclib 20
		gravestones: Gravestones v1.15
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lightmanscurrency: Lightman's Currency 1.20.1-1.0.1.1
		lithium: Lithium 0.11.2
		medievalorigins: Medieval Origins Revival 5.2.1+1.20.1
			additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
			common-protection-api: Common Protection API 1.0.0
		minecraft: Minecraft 1.20.1
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.1
		mr_true_ending: True Ending: Ender Dragon Overhaul 1.0.1b
		naturalist: Naturalist 4.0.3
		obscure_api: Obscure API 16
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				calio: Calio 1.11.0
				playerabilitylib: Pal 1.8.0
		origins-classes: Origins: Classes 1.7.0
		pehkui: Pehkui 3.7.11+1.14.4-1.20.2
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		puffish_skills: Pufferfish's Skills 0.10.0
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		simplyswords: Simply Swords 1.51.5-1.20.1
		sliceanddice: Create Slice & Dice 3.0.0
		spell_engine: Spell Engine 0.12.4+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		styledchat: Styled Chat 2.2.2+1.20.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.2+1.20.1
			player-data-api: Player Data API 0.2.2+1.19.3
			predicate-api: Predicate API 0.1.2+1.20
		styledplayerlist: Styled Player List 3.1.1+1.20.1
		terrablender: TerraBlender 3.0.0.169
		terralith: Terralith 2.4.11
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.8
		trinkets: Trinkets 3.7.1
		vcinteraction: Voice Chat Interaction 1.20.1-1.0.3
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.0+1.20
		vmp: Very Many Players 0.2.0+beta.7.102
		voicechat: Simple Voice Chat 1.20.1-2.4.32
		waystones: Waystones 14.1.2
		woods_and_mires: Woods and Mires 2.1.1+1.20.1
			com_typesafe_config: config 1.4.2
		wthit: wthit 8.4.3
	Server Running: true
	Player Count: 4 / 30; [class_3222['wicia123'/297814, l='ServerLevel[e11]', x=738.11, y=16.00, z=1.71], class_3222['edein_'/298065, l='ServerLevel[e11]', x=749.99, y=16.00, z=4.94], class_3222['mariusz9q'/300172, l='ServerLevel[e11]', x=748.38, y=18.06, z=5.60], class_3222['mmisia'/323251, l='ServerLevel[e11]', x=746.82, y=17.44, z=3.87]]
	Data Packs: vanilla, fabric, medievalorigins:tag_loader
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### Other Mods

```shell
indium
sodium
create + steams n rails + additions
farmersdelight + expanded
krypton
lazydfu
lithium
medievial origins + origins +classess
woodsandmires
```

**Comment by Xplodin** [comment]
create is causing the crash
Name: create:cart_assembler
