### ISSUE TITLE
Random  better end chunks cause crashes, unable to enter server due to crash. (Main island is fine) [Bug] 

### ISSUE THREAD

**Issue by omnii1** [quiqueck/BetterEnd#340]
### What happened?

whenever i enter random better end chunks on the outer islands, the game crashes and i am unable to get back into the server until someone forces me out via teleport. apologies if this is a duplicate!

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 1/24/24, 4:43 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5864()" because the return value of "net.minecraft.class_1606.method_5854()" is null
	at net.minecraft.class_1606.method_5678(class_1606.java:335)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.simulateBrushes(TerrestrialStepSoundGenerator.java:356)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.generateFootsteps(TerrestrialStepSoundGenerator.java:80)
	at eu.ha3.presencefootsteps.sound.SoundEngine.lambda$onFrame$1(SoundEngine.java:84)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at eu.ha3.presencefootsteps.sound.SoundEngine.onFrame(SoundEngine.java:81)
	at eu.ha3.presencefootsteps.PresenceFootsteps.lambda$onTick$1(PresenceFootsteps.java:96)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at eu.ha3.presencefootsteps.PresenceFootsteps.onTick(PresenceFootsteps.java:91)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bpc000$onEndTick(class_310.java:7997)
	at net.minecraft.class_310.method_1574(class_310.java:1807)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1606.method_5678(class_1606.java:335)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.simulateBrushes(TerrestrialStepSoundGenerator.java:356)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.generateFootsteps(TerrestrialStepSoundGenerator.java:80)
	at eu.ha3.presencefootsteps.sound.SoundEngine.lambda$onFrame$1(SoundEngine.java:84)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at eu.ha3.presencefootsteps.sound.SoundEngine.onFrame(SoundEngine.java:81)
	at eu.ha3.presencefootsteps.PresenceFootsteps.lambda$onTick$1(PresenceFootsteps.java:96)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at eu.ha3.presencefootsteps.PresenceFootsteps.onTick(PresenceFootsteps.java:91)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bpc000$onEndTick(class_310.java:7997)

-- Affected level --
Details:
	All players: 1 total; [class_746['omniii_'/27427, l='ClientLevel', x=-1250.52, y=93.00, z=-214.65]]
	Chunk stats: 16384, 19
	Level dimension: minecraft:the_end
	Level spawn location: World: (16,222,0), Section: (at 0,14,0 in 1,13,0; chunk contains blocks 16,0,0 to 31,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11344311 game time, 6556052 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Fabric Mods
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.class_310.method_1523(class_310.java:1080)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.StackOverflowError
	at net.fabricmc.fabric.impl.renderer.SpriteFinderImpl$Node.addInner(SpriteFinderImpl.java:109) **(this repeats a good 100 times)**
	
	
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		additionalentityattributes: Additionalentityattributes 1.0.0+1.18.1
		adorn: Adorn 3.3.1+1.18.1
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		amplified_nether: Amplified Nether for Fabric 1.0.1
		animal_origins_18: Animal Origins 1.0.0
		apoli: Apoli 2.2.4
		apugli: Apugli 1.5.1
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.2
		architectury: Architectury 3.9.66
		autoconfig1u: Auto Config v1 Updated 3.2.2
		backslot: BackSlot 1.2.5
		backslotaddon: BackSlot Addon 1.0.8
		bclib: BCLib 1.3.5
		bendy-lib: Bendy api 2.0.4
		betterdungeons: YUNG's Better Dungeons 1.18-1.0
		betterend: Better End 1.0.3
		bettermineshafts: YUNG's Better Mineshafts 1.18.1-1.0
		betternether: Better Nether 6.0.12
		betterthirdperson: Better Third Person 1.6.0
		biomemakeover: Biome Makeover 1.18.1-1.4.8
		caffeineconfig: CaffeineConfig 1.0.0
		calio: Calio 1.4.2
		capes: Capes 1.2.2+1.18
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		chunky: Chunky 1.2.164
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config: Cloth Config v6 6.2.62
		collective-fabric: Collective (Fabric) 4.9
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		crawl: Crawl 0.10.2
		creeperoverhaul: Creeper Overhaul 0.3.0
		dashloader: DashLoader 4.0.0
		dev_quantumfusion_hyphen: Hyphen 0.2.2
		dev_quantumfusion_taski: Taski 1.1.0
		dryadorigin: Dryad Origin 1.1.0
		dual_riders: DualRiders 1.0.5
		earthbounds: Earthbounds 1.0.5b
		ecologics: Ecologics 1.3.0
		edenring: EdenRing 0.3.0
		effective: Effective 1.2
		emotecraft: Emotecraft 2.1.2
		end_origins: End Origins 1.0.0
		endportalrecipe-fabric: End Portal Recipe (Fabric) 2.6
		extrakeybinds: ThatRobins Extra Origins Keybinds 1.18-0.1.0
		extraorigins: Extra Origins 1.18-9
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.13.3
		fancymenu: FancyMenu 2.7.2
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 1.7.1
		geckolib3: Geckolib 3.0.33
		genesis: Genesis 1.18.1-1.0.0
		goosik-config: goosik-config 0.2.0
		gravestones: Simple Gravestones 0.5
		graveyard_biomes: The Graveyard Biomes 1.0
		gravit_origin: Gravitonian Origin 1.0.0
		gravitychanger: GravityChanger 0.3.0
		grounded_origins: Grounded Origins 1.1.2
		guardvillagers: Guard Villagers Fabric 1.18.1-1.0.11
		here-be-no-dragons: Here be no Dragons! 1.0.0
		ibarnorigins: ibarn's origins addon 1.0.5
		indium: Indium 1.0.2-alpha3+mc1.18.1
		infinitemusic: Infinite Music 1.5.1
		infusion_table: Infusion Table 1.0.5
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		kirin: Kirin UI 1.10.0-beta.2
		koboldorigin: Kobold Origin 1.6
		konkrete: Konkrete 1.3.3
		locksmith: Locksmith 1.0.1
		logical_zoom: Logical Zoom 0.0.13
		medievalmusic: Medieval Music Mod 1.18-1.3
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		moborigins: Mob Origins 1.8.0
		modid: Origins: Umbrellas 1.5.0
		modmenu: Mod Menu 3.0.1
		moretags: More Tags 2.0.3
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.1+1.18.1
		mrplaguewarper: MrPlague's Warper Origin 1.0.6
		mythicmounts: Mythic Mounts 1.18.1-7.0
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		notenoughanimations: NotEnoughAnimations 1.6.0
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		origins: Origins 1.3.2
		paperdoll: PaperDoll 1.1.0-mc1.18
		patchouli: Patchouli 1.18.1-65-FABRIC
		paxi: Paxi 1.18-1.0
		pehkui: Pehkui 3.3.2+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		playerabilitylib: Pal 1.3.0
		pollen: Pollen 1.4.3
		polymorph: Polymorph 0.0.20-1.18.2
		presencefootsteps: Presence Footsteps 1.4.0
		rammling: Goat Origin 1.0.0
		ratsmischief: Rat's Mischief 1.3.5
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.4.456
		roughlyenoughresources: Roughly Enough Resources 2.4.1
		seedfix: Seed Fix 1.0.0
		sentimentality3: Sentimentality 3 1.4.10
		skinlayers: 3d Skin Layers 1.4.6-mc1.18.2
		skinswapper: Skin Swapper 3.1.1
		skylorlib: SkyLib 1.2.1
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.4.0
		terrablender: TerraBlender 1.1.0.77
		terralith: Terralith for Fabric 2.0.12
		toomanyorigins: TooManyOrigins 0.4.2
		twigs: Twigs 1.1.2
		visuality: Visuality 0.4.1
		voicechat: Simple Voice Chat 1.18.1-2.2.32
		wildlife: Wildlife 1.18-1.0
		wthit: wthit 4.5.5
		yungsapi: YUNG's API 1.18-Fabric-36
		yungsextras: YUNG's Extras 1.18.1-1.0
	Launched Version: fabric-loader-0.13.3-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 6600 GL version 3.2.0 Core Profile Context 23.9.1.231121, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5500 

### BetterEnd

1.0.3

### BCLib

1.3.5

### Fabric API

0.46.6+1.18

### Fabric Loader

0.13.3

### Minecraft

Older

**Comment by lostyawolfer** [comment]
encountered that too, here's a video. however in my case this happened on main island and it happened after i went through custom-built eternal portal (it wasn't first time i went through it, it generated properly, but now for some reason it crashed)

https://youtu.be/jnyWObFvCBU
