### ISSUE TITLE
[Bug] crash when rendering block entity and tesselating block model

### ISSUE THREAD

**Issue by ShuitOnDiscord** [quiqueck/BetterEnd#363]
### What happened?

game freezes until forced to close when in the end. completely stuck when joining the world after the initial freeze. continuity causes an error with "rendering block entity", no clue what causes the other error

### BetterEnd

4.30.1

### BCLib

3.30.1

### Fabric API

0.96.4

### Fabric Loader

0.15.7

### Minecraft

1.20.4

### Relevant log output

```shell
net.minecraft.class_148: Rendering Block Entity
	at net.minecraft.class_824.method_3554(class_824.java:111) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:79) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369) ~[Sodium.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.handler$col000$nvidium$overrideEntityRenderer(SodiumWorldRenderer.java:1568) ~[Sodium.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java) ~[Sodium.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271) ~[Sodium.jar:?]
	at net.minecraft.class_761.handler$dni000$sodium$onRenderBlockEntities(class_761.java:14331) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1146) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1098) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:866) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.7-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property class_2754{name=north, clazz=class net.minecraft.class_4778, values=[none, low, tall]} as it does not exist in Block{diagonalwalls:betterend/helix_tree_wall}
	at net.minecraft.class_2688.method_11654(class_2688.java:98) ~[client-intermediary.jar:?]
	at org.betterx.bclib.blocks.BaseWallBlock.lambda$getModelVariant$0(BaseWallBlock.java:85) ~[0-BCLib.jar:?]
	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:583) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.4+78d798af4f-46b33a48920e2716.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:53) ~[Continuity.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.4+78d798af4f-46b33a48920e2716.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:72) ~[Continuity.jar:?]
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.render(NonTerrainBlockRenderContext.java:66) ~[0-Indium.jar:?]
	at net.minecraft.class_778.handler$cbk000$indium$hookRender(class_778.java:553) ~[client-intermediary.jar:?]
	at net.minecraft.class_778.method_3374(class_778.java) ~[client-intermediary.jar:?]
	at biomesoplenty.client.renderer.AnomalyRenderer.render(AnomalyRenderer.java:42) ~[BiomesOPlenty.jar:?]
	at biomesoplenty.client.renderer.AnomalyRenderer.method_3569(AnomalyRenderer.java:21) ~[BiomesOPlenty.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3554(class_824.java:104) ~[client-intermediary.jar:?]
	... 15 more
```
```
[20:15:37] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Tesselating block model
	at net.minecraft.class_824.method_3554(class_824.java:111) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:79) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369) ~[Sodium.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308) ~[Sodium.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271) ~[Sodium.jar:?]
	at net.minecraft.class_761.handler$dmo000$sodium$onRenderBlockEntities(class_761.java:14331) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1146) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1098) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:866) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.7-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property class_2754{name=north, clazz=class net.minecraft.class_4778, values=[none, low, tall]} as it does not exist in Block{diagonalwalls:betterend/jellyshroom_wall}
	at net.minecraft.class_2688.method_11654(class_2688.java:98) ~[client-intermediary.jar:?]
	at org.betterx.bclib.blocks.BaseWallBlock.lambda$getModelVariant$0(BaseWallBlock.java:85) ~[0-BCLib.jar:?]
	at net.minecraft.class_1095.method_4707(class_1095.java:1053) ~[client-intermediary.jar:?]
	at net.minecraft.class_778.method_3361(class_778.java:70) ~[client-intermediary.jar:?]
	at net.minecraft.class_778.method_3374(class_778.java:48) ~[client-intermediary.jar:?]
	at biomesoplenty.client.renderer.AnomalyRenderer.render(AnomalyRenderer.java:42) ~[BiomesOPlenty.jar:?]
	at biomesoplenty.client.renderer.AnomalyRenderer.method_3569(AnomalyRenderer.java:21) ~[BiomesOPlenty.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3554(class_824.java:104) ~[client-intermediary.jar:?]
	... 14 more
```

### Other Mods

sorry
```shell
[18:43:01] [main/INFO]: Loading 181 mods:
	- accurateblockplacement 1.2.1
	- ambientsounds 5.3.5
	- appleskin 2.5.1+mc1.20.3
	   \-- cloth-config 13.0.114
	        \-- cloth-basic-math 0.6.1
	- balm-fabric 9.0.6
	- bclib 3.30.1
	   \-- wunderlib 1.30.0
	- betteranimationscollection 20.4.0
	- betterend 4.30.1
	- betterthirdperson 1.9.0
	- biomesoplenty 19.0.0.63
	   |-- com_electronwill_night-config_core 3.6.7
	   |-- com_electronwill_night-config_toml 3.6.7
	   \-- net_jodah_typetools 0.6.3
	- blur 3.2.0
	   \-- satin 1.15.0
	- boatiview 0.0.5
	- cameraoverhaul 1.4.0-fabric-universal
	- camerautils 1.20.4-1.0.9
	- chat_heads 0.10.32
	- chunky 1.3.138
	- cleardespawn 1.1.15
	- clickthrough 1.20.4-fabric0.91.2-0.4.1
	   |-- crowdin-translate 1.4+1.19.3
	   \-- gbfabrictools 1.4+1.20
	- collective 7.40
	- colorfulsubtitles 1.4.0
	- continuity 3.0.0-beta.4+1.20.2
	- creativecore 2.11.16
	   \-- net_neoforged_bus 7.2.0
	- ctov 3.4.2
	- detailab 2.6.3+1.20.4-fabric
	- diagonalfences 20.4.0
	   \-- diagonalblocks 20.4.2
	- diagonalwalls 20.4.0
	   \-- diagonalblocks 20.4.2
	- diagonalwindows 20.4.0
	   \-- diagonalblocks 20.4.2
	- do_a_barrel_roll 3.3.8+1.20.4
	   |-- cicada 0.5.0+1.20.2-plus
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- mixinsquared 0.1.1
	- dynamic_fps 3.4.2
	- dynamiccrosshair 7.7+1.20.4
	   \-- yaclx 1.12+1.20.2
	- eatinganimationid 1.20+1.9.5
	- emi 1.1.3+1.20.4+fabric
	- entityculling 1.6.3.1
	- fabric-api 0.96.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.14+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.3+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.3+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.25+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.8+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.64+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.13+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.19+58f8c0124f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- fallingleaves 1.15.4
	- firstperson 2.3.4
	- forgeconfigapiport 20.4.3
	- fsit v1.5.1-1.20.2
	- glitchcore 1.0.0.59
	   |-- com_electronwill_night-config_core 3.6.7
	   |-- com_electronwill_night-config_toml 3.6.7
	   \-- net_jodah_typetools 0.6.3
	- healingcampfire 5.3
	- iceberg 1.1.18
	- incendium 5.3.4
	- indium 1.0.30+mc1.20.4
	- infinitetrading 4.3
	- inventoryhud 3.4.19
	- invmove 0.8.5
	- iris 1.7.0-snapshot+mc1.20.4-5983468
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- jei 17.3.0.49
	- lambdynlights 2.3.4+1.20.4
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.3+1.20.2
	- lazydfu 0.1.3
	- legendarytooltips 1.4.5
	- litematica 0.17.2
	- loadmyresources 1.0.4
	- malilib 0.18.1
	- midnightlib 1.5.3
	- mine-spawners 1.0
	- minecraft 1.20.4
	- mixintrace 1.1.1+1.17
	- modmenu 9.0.0
	- nohostilesaroundcampfire 5.9
	- notenoughanimations 1.7.1
	- nvidium 0.2.6-beta
	- presencefootsteps 1.11.2
	   \-- kirin 1.17.0+1.20.4
	- prism 1.0.6
	- puzzleslib 20.4.39
	- reeses-sodium-options 1.7.2+mc1.20.4-build.102
	- replaymod 1.20.4-2.6.15
	- resclone 1.11.3
	   |-- libjf-base 3.14.1
	   \-- libjf-config-core-v2 3.14.1
	- skinlayers3d 1.6.2
	- sodium 0.5.8+mc1.20.4
	- sodium-extra 0.5.4+mc1.20.4-build.116
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sound_physics_remastered 1.20.4-1.3.1
	- spark 1.10.60
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- spawnanimations 1.9.4+mod
	- starlight 1.1.3+fabric.f5dcd1a
	- statuseffecttimer 1.2.0+1.20
	- taxfreelevels 1.3.9
	- tectonic 2.2.1
	- terrablender 3.3.0.12
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- tooltipfix 1.1.1-1.20
	- trinkets 3.8.1
	   |-- cardinal-components-base 5.4.0
	   \-- cardinal-components-entity 5.4.0
	- universal-graves 3.2.1+1.20.3
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.3.0+1.20.3
	   |-- polymer-core 0.7.5+1.20.4
	   |    |-- polymer-networking 0.7.5+1.20.4
	   |    |    \-- polymer-common 0.7.5+1.20.4
	   |    |         \-- packet_tweaker 0.5.1+1.20.4
	   |    \-- polymer-registry-sync-manipulator 0.7.5+1.20.4
	   |-- polymer-resource-pack 0.7.5+1.20.4
	   |    \-- polymer-common 0.7.5+1.20.4
	   |         \-- packet_tweaker 0.5.1+1.20.4
	   |-- polymer-virtual-entity 0.7.5+1.20.4
	   |    \-- polymer-common 0.7.5+1.20.4
	   |         \-- packet_tweaker 0.5.1+1.20.4
	   |-- predicate-api 0.3.0+1.20.2
	   |-- server_translations_api 2.2.0+1.20.3-rc1
	   \-- sgui 1.4.1+1.20.4
	- vcinteraction 1.20.4-1.0.6
	- visuality 0.7.3+1.20.4
	- visualoverhaul 5.1.0
	- visualworkbench 20.4.1
	- voicechat 1.20.4-2.5.9
	- waterdripsound 1.19-0.3.2
	- waystones 16.0.4
	- xaerominimap 24.0.2
	- xaeroworldmap 1.38.1
```

**Comment by ShuitOnDiscord** [comment]
issue was with diagonal walls. im terribly sorry for wasting your time and making an unnecessary issue
