### ISSUE TITLE
Creating a new world button crashing when nullscaped and betterend installed 

### ISSUE THREAD

**Issue by FelixAndre** [quiqueck/BetterEnd#39]
### What happened?

When creating a new world with betterend and nullscaped installed the game crashes. 

### BetterEnd

2.0.5

### BCLib

2.0.10

### Fabric API

0.57.0+1.19

### Fabric Loader

0.14.7-1.19

### Minecraft

1.19

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 11/07/22 23:01
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null
	at net.minecraft.class_3503.md4ae001$lambda$loadTagInject$1$4(class_3503.java:1555)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_3503.handler$cma000$loadTagInject(class_3503.java:1553)
	at net.minecraft.class_3503.method_33174(class_3503.java:68)
	at net.minecraft.class_3503.method_33176(class_3503.java:163)
	at net.minecraft.class_3505.method_33181(class_3505.java:64)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:494)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:494)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1171)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, fabric-copper-golem/copper_golem, charmonium/journeyman, minecraft/supporteatinganimation, xali-s-Enchanted-Books-16x-v0.10.1.zip

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2873209512 bytes (2740 MiB) / 4697620480 bytes (4480 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8476
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f91
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1278
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26942.64
	Virtual memory used (MB): 16398.15
	Swap memory total (MB): 10752.00
	Swap memory used (MB): 350.78
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		additionalstructures: Additional Structures 4.0.0
		advancednetherite: Advanced Netherite 1.6.1-1.19
		advancementplaques: Advancement Plaques 1.4.5
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19
		aqupdcaracal: Caracal mob 1.19-1.3.8
		architectury: Architectury 5.6.22
		axolotlitemfix: Axolotl Item Fix 1.1.3
		bclib: BCLib 2.0.10
		betteradvancements: Better Advancements 0.2.1.134
		betterend: Better End 2.0.5
		bettervillage: Better Village 1.0.1
		biomemakeover: Biome Makeover 1.19-1.5.7
		blockus: Blockus 2.5.1+1.19
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0
		bookshelf: Bookshelf 14.0.3
		capybara: Capybara 1.0.4
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmonium: Charmonium 4.1.0
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 6.0.0-beta.2+1.19
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			spectrelib: SpectreLib 0.4.0+1.19
		dawn: Dawn API 3.5.0
		dragonloot: DragonLoot 1.1.1
		eatinganimationid: Eating Animation 1.8.1
		ecologics: Ecologics 2.0.0
		enchdesc: EnchantmentDescriptions 11.0.4
		endrem: End Remastered 5.1.0
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-copper-golem: Copper Golem 1.0.5+1.19
		fabricloader: Fabric Loader 0.14.7
		fallingtree: FallingTree 3.6.1
		farmersdelight: Farmer's Delight 1.19-0.3.0
		flytre_lib: FlytreLib 1.8.8
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		fwaystones: Fabric Waystones 3.0.0
		geckolib3: Geckolib 3.1.2
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 1.10
			omega-config: OmegaConfig 1.2.2-1.18.1
		grindenchantments: Grind Enchantments 2.0.0+1.19
		iceberg: Iceberg 1.0.38
		impactfulweather: Biome Particle Weather 3.4.9
		imst: Immersive structures 2.0.2
		incendium: Incendium + Seed Fix 5.1.0
		indium: Indium 1.0.4+mc1.19
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		jade: Jade 7.1.2
		java: OpenJDK 64-Bit Server VM 17
		libraryferret: Library Ferret 1.0.3
		mavm: More Axolotl Variants Mod 1.0.8a
		minecraft: Minecraft 1.19
		modid: Creatures Of The Snow 2.2.0+1.19
		modmenu: Mod Menu 4.0.0
		moreblockbricks: More Block Bricks 1.4.0
		morevillagers: More Villagers 4.0.1
		naturalist: Naturalist 2.0.1
		nears: Nears 1.1.8
		nullscape: Nullscape 1.2
		pipe: Pipe 1.8.3
		quartzelv: Quartz Elevator 2.1.3+1.19
		roughlyenoughitems: Roughly Enough Items 9.0.475
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		structory: Structory 1.0.1
		t_and_t: Towns and Towers - Structure Add-on 1.7
		thonkutil: ThonkUtil 2.15.2+1.19
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.0+82e731da57
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.1+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.1+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.1+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.1+8ff533c957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.1+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.1+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.1+8ff533c957
		totw_additions: Towers of the Wild: Additions 1.2.3
		travelersbackpack: Traveler's Backpack 1.19-8.0.1
		trinkets: Trinkets 3.4.0
		universal_ores: Universal Ores 1.4.0
		walljump: Wall-Jump! 1.4.3+1.19
		xaerominimap: Xaero's Minimap 22.9.2
		xaeroworldmap: Xaero's World Map 1.25.1
		yigd: You're in Grave Danger 1.4.1
	Loaded Shaderpack: ComplementaryShaders_v4.5.1.zip
		Profile: HIGH (+0 options changed by user)
	Launched Version: fabric-loader-0.14.7-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.78, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, fabric-copper-golem/copper_golem (incompatible), charmonium/journeyman, minecraft/supporteatinganimation (incompatible), file/xali-s-Enchanted-Books-16x-v0.10.1.zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
```

### Other Mods

```shell
AdditionalAdditions 
Additional Structures
Advanced Netherite 
Advancement plaques
animal feeding trough
architectury 
axolotl item fix
BetterAdvancement Fabric
Bettervillage fabric
biomemakeover
Biome weather effects 
blokus
bookshelf
capybara
caracal
charm fabric
charmonium
cloth config
clumps 
comforts
copper golem 
Creatures from the snow
dawn
dragonloot
eating animation
ecologics
enchantment descriptions
fabric api
end remastered 
falling tree
farmers delight
fyltre lib
ForgeconfigAPIport
geckolib 
goblin traders
grind enchantments
iceberg
IMST
incendium
InventoryHUD
iris mc
jade
Libraryferret
More axolotls variants mod
modmenu
more block bricks
morevillagers
naturalist
nears fabric
Nullscape
pipe 1.19-1.8.3 fabric
quartz elevator
Roughly enough items
sodium fabric
Structory
The graveyard
thonkutil
towns and towers additions
travelers backpack
trinkets
universal ores
walljump fabric 
wraith waystones
Xaeros minimap
Xaeros worldmap
youre in grave danger
```

**Comment by quiqueck** [comment]
Hm, can't seem to reproduce the issue. Would you please try again with the latest versions of the mods?

**Comment by Schummel-8** [comment]
Had the same issue and i think there is a problem with the trinket mod. You have to make yourself a datapack to fix that and change the `group.json` file in `data/trinkets/slots/hand` to 

```
{
  "slot_id": 4
}

```
Maybe that fixes it.
