### ISSUE TITLE
crash when using the vanilla anvil and I suppose its variants[Bug]

### ISSUE THREAD

**Issue by Fulanote** [quiqueck/BetterEnd#409]
### What happened?

I wanted to rename an item putting it in the vanilla anvil and the game crashed

### BetterEnd

21.0.0

### BCLib

21.0.3

### Fabric API

0.100.1

### Fabric Loader

0.15.11

### Minecraft

1.20.4

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-06-28 23:55:29
Description: Container click

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7947()" because "material" is null
	at org.betterx.bclib.recipes.AnvilRecipe.matches(AnvilRecipe.java:161)
	at org.betterx.bclib.recipes.AnvilRecipe.matches(AnvilRecipe.java:99)
	at org.betterx.bclib.recipes.AnvilRecipe.method_8115(AnvilRecipe.java:45)
	at net.minecraft.class_1863.method_42297(class_1863.java:106)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_1863.method_17877(class_1863.java:108)
	at net.minecraft.class_1706.handler$zzf000$bclib$bcl_updateOutput(class_1706.java:631)
	at net.minecraft.class_1706.method_24928(class_1706.java)
	at net.minecraft.class_1706.method_7625(class_1706.java:355)
	at net.minecraft.class_471.method_2403(class_471.java:85)
	at net.minecraft.class_342.method_1874(class_342.java:154)
	at net.minecraft.class_342.method_1883(class_342.java:262)
	at net.minecraft.class_342.method_1872(class_342.java:275)
	at net.minecraft.class_342.method_1852(class_342.java:102)
	at net.minecraft.class_471.method_7635(class_471.java:140)
	at net.minecraft.class_1703.method_34246(class_1703.java:219)
	at net.minecraft.class_1703.method_7623(class_1703.java:176)
	at net.minecraft.class_1703.method_7609(class_1703.java:589)
	at net.minecraft.class_4861.method_7609(class_4861.java:103)
	at net.minecraft.class_4861$3.method_5431(class_4861.java:96)
	at net.minecraft.class_1277.redirect$bda000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:543)
	at net.minecraft.class_1277.method_5447(class_1277.java:142)
	at net.minecraft.class_1735.method_7673(class_1735.java:75)
	at net.minecraft.class_1735.method_48931(class_1735.java:66)
	at net.minecraft.class_1735.method_53512(class_1735.java:63)
	at net.minecraft.class_1703.method_7616(class_1703.java:661)
	at net.minecraft.class_4861.method_7601(class_4861.java:147)
	at net.minecraft.class_1703.method_30010(class_1703.java:394)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:448)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25402(class_465.java:349)
	at net.minecraft.class_471.method_25402(class_471.java:624)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.betterx.bclib.recipes.AnvilRecipe.matches(AnvilRecipe.java:161)
	at org.betterx.bclib.recipes.AnvilRecipe.matches(AnvilRecipe.java:99)
	at org.betterx.bclib.recipes.AnvilRecipe.method_8115(AnvilRecipe.java:45)
	at net.minecraft.class_1863.method_42297(class_1863.java:106)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_1863.method_17877(class_1863.java:108)
	at net.minecraft.class_1706.handler$zzf000$bclib$bcl_updateOutput(class_1706.java:631)
	at net.minecraft.class_1706.method_24928(class_1706.java)
	at net.minecraft.class_1706.method_7625(class_1706.java:355)
	at net.minecraft.class_471.method_2403(class_471.java:85)
	at net.minecraft.class_342.method_1874(class_342.java:154)
	at net.minecraft.class_342.method_1883(class_342.java:262)
	at net.minecraft.class_342.method_1872(class_342.java:275)
	at net.minecraft.class_342.method_1852(class_342.java:102)
	at net.minecraft.class_471.method_7635(class_471.java:140)
	at net.minecraft.class_1703.method_34246(class_1703.java:219)
	at net.minecraft.class_1703.method_7623(class_1703.java:176)
	at net.minecraft.class_1703.method_7609(class_1703.java:589)
	at net.minecraft.class_4861.method_7609(class_4861.java:103)
	at net.minecraft.class_4861$3.method_5431(class_4861.java:96)
	at net.minecraft.class_1277.redirect$bda000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:543)
	at net.minecraft.class_1277.method_5447(class_1277.java:142)
	at net.minecraft.class_1735.method_7673(class_1735.java:75)
	at net.minecraft.class_1735.method_48931(class_1735.java:66)
	at net.minecraft.class_1735.method_53512(class_1735.java:63)
	at net.minecraft.class_1703.method_7616(class_1703.java:661)
	at net.minecraft.class_4861.method_7601(class_4861.java:147)
	at net.minecraft.class_1703.method_30010(class_1703.java:394)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:448)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25402(class_465.java:349)
	at net.minecraft.class_471.method_25402(class_471.java:624)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)

-- Click info --
Details:
	Menu Type: minecraft:anvil
	Menu Class: net.minecraft.class_1706
	Slot Count: 39
	Slot: 31
	Button: 0
	Type: QUICK_MOVE
Stacktrace:
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:448)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25402(class_465.java:349)
	at net.minecraft.class_471.method_25402(class_471.java:624)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_471
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 107.485s
	Wall uptime: 91.996s
	High-res time: 83.470s
	Client ticks: 1399 ticks / 69.950s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['MrJulis'/30, l='ClientLevel', x=11.38, y=64.00, z=-3.31]]
	Chunk stats: 1369, 241
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 280 game time, 280 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 155

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Default-Dark-Mode-1.20.3-0.86-030303-1-1-0C0C0C-767676-(2024.6.0).zip, fabric, bclib, betterend, betternether, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, wover, wover-block, wover-core, wover-events, wover-generator, wover-preset, wover-surface, wover-ui, wunderlib

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 567914408 bytes (541 MiB) / 2684354560 bytes (2560 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21912.14
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 4096.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.5599
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 38269.32
	Virtual memory used (MiB): 13491.43
	Swap memory total (MiB): 22528.00
	Swap memory used (MiB): 35.71

	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bclib: BCLib 21.0.3
		betterend: Better End 21.0.0
		betternether: Better Nether 21.0.3
		fabric-api: Fabric API 0.100.1+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.65+b559734490
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b9990
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a790
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a790
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.11+b559734490
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.12+7f945d5b90
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.2.1+d153f34490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a790
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.22+6a6dfa1990
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.6+16c4ae2590
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9990
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b9990
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8c90
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+00ab0a6390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.9+98a7dbbb90
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.9+6573ed8c90
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c90
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b90
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+686dcdce90
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.10+d132107690
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c90
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.8+6573ed8c90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.21+b9828ba390
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6b90
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.3+cc9f121a90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b559734490
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f34490
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.3+b559734490
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.78+b559734490
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.12+b559734490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8c90
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21
		wover: WorldWeaver 21.0.4
			wover-biome: WorldWeaver - Biome API 21.0.4
			wover-block: WorldWeaver - Block and Item API 21.0.4
			wover-common: WorldWeaver - Common API 21.0.4
			wover-core: WorldWeaver - Core API 21.0.4
			wover-datagen: WorldWeaver - Datagen API 21.0.4
			wover-events: WorldWeaver - Events API 21.0.4
			wover-feature: WorldWeaver - Feature API 21.0.4
			wover-generator: WorldWeaver - World Generator API 21.0.4
			wover-item: WorldWeaver - Item API 21.0.4
			wover-math: WorldWeaver - Math API 21.0.4
			wover-preset: WorldWeaver - World Preset API 21.0.4
			wover-recipe: WorldWeaver - Recipe API 21.0.4
			wover-structure: WorldWeaver - Structure API 21.0.4
			wover-surface: WorldWeaver - Surface API 21.0.4
			wover-tag: WorldWeaver - Tag API 21.0.4
			wover-ui: WorldWeaver - UI API 21.0.4
			wunderlib: WunderLib 21.0.2
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.99, NVIDIA Corporation
	Window size: 1920x1080
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 15/15 chunks
	Resource Packs: vanilla, file/Default-Dark-Mode-1.20.3-0.86-030303-1-1-0C0C0C-767676-(2024.6.0).zip (incompatible), fabric, bclib, betterend, betternether, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, wover, wover-block, wover-core, wover-events, wover-generator, wover-preset, wover-surface, wover-ui, wunderlib
	Current Language: es_es
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 4600H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['MrJulis'/30, l='ServerLevel[Mundo nuevo]', x=11.38, y=64.00, z=-3.31]]
	Active Data Packs: vanilla, fabric, bclib, betterend, betternether, fabric-convention-tags-v2, wover-generator, wover-preset, wover-surface, wover-tag
	Available Data Packs: bclib, betterend, betterend:nourish_extensions, betterend:patchouli_extensions, betternether, betternether:vanilla-hammers_extensions, betternether:vanillaexcavators_extensions, bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla, wover-generator, wover-preset, wover-surface, wover-tag
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -1822751450725518730
```

### Other Mods

```shell
better-nether-21.0.3
worldweaver-21.0.4
fabric-api-0.100.1+1.21
```

**Comment by RiskE80T** [comment]
happens to me too, it also deletes whatever item you were trying to put in the anvil

**Comment by Griffin-Zara** [comment]
I'm having the same issue. is there a solution?

**Comment by RiskE80T** [comment]
> I'm having the same issue. is there a solution?

Not that I know of, I added it to its own modpack with nothing in it and it was still crashing

**Comment by junieclipse** [comment]
Glad it's not just me. I was able to work around the ladders issue, but nothing I've tried to hotfix this has worked.

**Comment by BabyPoto** [comment]
> Glad it's not just me. I was able to work around the ladders issue, but nothing I've tried to hotfix this has worked.

It's happening across the board.

**Comment by RiskE80T** [comment]
> > Glad it's not just me. I was able to work around the ladders issue, but nothing I've tried to hotfix this has worked.
> 
> 
> 
> It's happening across the board.
> 
> 

I'm pretty sure it's a bclib issue
