### ISSUE TITLE
[Bug] crashes server with either farmers delight or earth to java mobs installed

### ISSUE THREAD

**Issue by ChristianKilduff** [quiqueck/BetterEnd#42]
### What happened?

server would crash b4 startup

### BetterEnd

2.0.9

### BCLib

2.0.16

### Minecraft

1.19

### Relevant log output

```shell
[21:29:34] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'earthtojavamobs'!
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
	at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
	Suppressed: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:worldgen/configured_feature / farmersdelight:patch_wild_cabbages])
		at net.minecraft.util.registry.SimpleRegistry.assertNotFrozen(SimpleRegistry:81) ~[?:?]
		at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:91) ~[?:?]
		at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:87) ~[?:?]
		at net.fabricmc.fabric.impl.registry.sync.DynamicRegistrySync.lambda$setupSync$1(DynamicRegistrySync.java:63) ~[fabric-registry-sync-v0-0.9.16+92cf9a3ea9-4f8772a3dede958e.jar:?]
		at net.minecraft.util.registry.SimpleRegistry.md91fde7$lambda$new$0$5(SimpleRegistry:1096) ~[?:?]
		at net.minecraft.util.registry.SimpleRegistry.handler$bhb000$setPost(SimpleRegistry:1174) ~[?:?]
		at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:130) ~[?:?]
		at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:87) ~[?:?]
		at net.minecraft.util.registry.SimpleRegistry.add(SimpleRegistry:135) ~[?:?]
		at net.minecraft.util.registry.Registry.register(Registry:508) ~[?:?]
		at net.minecraft.util.registry.Registry.register(Registry:504) ~[?:?]
		at com.nhoryzon.mc.farmersdelight.registry.ConfiguredFeaturesRegistry.registerAll(ConfiguredFeaturesRegistry.java:80) ~[farmers-delight-fabric-1.19-0.3.0.jar:?]
		at com.nhoryzon.mc.farmersdelight.FarmersDelightMod.onInitialize(FarmersDelightMod.java:69) ~[farmers-delight-fabric-1.19-0.3.0.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
		at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at slexom.earthtojava.Earth2JavaMod.initialize(Earth2JavaMod.java:60) ~[earthtojavamobs-fabric-mc1.19-1.9.2+1.19.jar:?]
	at slexom.earthtojava.fabric.Earth2JavaModFabric.onInitialize(Earth2JavaModFabric.java:49) ~[earthtojavamobs-fabric-mc1.19-1.9.2+1.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:worldgen/configured_feature / earthtojavamobs:e2j_flowers])
	at net.minecraft.util.registry.SimpleRegistry.assertNotFrozen(SimpleRegistry:81) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:91) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:87) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.DynamicRegistrySync.lambda$setupSync$1(DynamicRegistrySync.java:63) ~[fabric-registry-sync-v0-0.9.16+92cf9a3ea9-4f8772a3dede958e.jar:?]
	at net.minecraft.util.registry.SimpleRegistry.md91fde7$lambda$new$0$5(SimpleRegistry:1096) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.handler$bhb000$setPost(SimpleRegistry:1174) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:130) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:87) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.add(SimpleRegistry:135) ~[?:?]
	at net.minecraft.util.registry.Registry.register(Registry:508) ~[?:?]
	at net.minecraft.util.registry.Registry.register(Registry:504) ~[?:?]
	at dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl.register(RegistriesImpl.java:211) ~[architectury-5.7.28-fabric.jar:?]
	at slexom.earthtojava.init.features.ConfiguredFeatureInit.<clinit>(ConfiguredFeatureInit.java:19) ~[earthtojavamobs-fabric-mc1.19-1.9.2+1.19.jar:?]
	at slexom.earthtojava.Earth2JavaMod.initialize(Earth2JavaMod.java:60) ~[earthtojavamobs-fabric-mc1.19-1.9.2+1.19.jar:?]
	at slexom.earthtojava.fabric.Earth2JavaModFabric.onInitialize(Earth2JavaModFabric.java:49) ~[earthtojavamobs-fabric-mc1.19-1.9.2+1.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more


```

### Other Mods

```shell
- additionaladditions 5.0.1
	- additionalentityattributes 1.0.0+1.19 via apoli
	- adorn 3.5.4+1.19
	- advanced_runtime_resource_pack 0.6.2 via secretrooms
	- adventure-platform-fabric 5.4.0-SNAPSHOT via minimotd-fabric
	- anthropophagy 1.19-2
	- apoli 2.5.0 via origins
	- architectury 5.7.28
	- autoconfig1u 3.4.0 via disfabric
	- backslot 1.2.8
	- bclib 2.0.16
	- betterend 2.0.9
	- blue_endless_jankson 1.2.1 via jankson
	- calio 1.7.0 via apoli
	- cardinal-components-base 5.0.0-beta.1 via anthropophagy
	- cardinal-components-entity 5.0.0-beta.1 via anthropophagy
	- charm 4.1.2
	- chisel 1.4.6
	- chunky 1.2.217
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.72
	- cloud 1.7.0 via mods-command
	- cloud_commandframework_cloud-brigadier_ 1.7.0 via cloud
	- cloud_commandframework_cloud-core_ 1.7.0 via cloud
	- cloud_commandframework_cloud-minecraft-extras 1.7.0 via mods-command
	- cloud_commandframework_cloud-services_ 1.7.0 via cloud
	- collective-fabric 4.27
	- com_electronwill_night-config_core 3.6.2 via charm
	- com_electronwill_night-config_toml 3.6.2 via charm
	- com_fasterxml_jackson_core_jackson-annotations 2.13.1 via disfabric
	- com_fasterxml_jackson_core_jackson-core 2.13.1 via disfabric
	- com_fasterxml_jackson_core_jackson-databind 2.13.1 via disfabric
	- com_google_code_findbugs_jsr305 3.0.2 via disfabric
	- com_konghq_unirest-java_standalone 3.13.4 via disfabric
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_neovisionaries_nv-websocket-client 2.14 via disfabric
	- com_squareup_okhttp3_okhttp 3.13.0 via disfabric
	- com_squareup_okio_okio 1.17.2 via disfabric
	- com_typesafe_config 1.4.2 via confabricate
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- compacthelpcommand-fabric 1.3
	- confabricate 3.0.0-SNAPSHOT+4.1.2 via mods-command
	- convenient-mobgriefing 2.0.2
	- disfabric 1.3.9
	- earthtojavamobs 1.9.2
	- ecologics 2.1.1
	- egg-of-capitalism 3.1
	- extraorigins 1.19-1
	- fabric 0.56.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.13+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.5+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.1+cda9839ba9 via fabric
	- fabric-commands-v0 0.2.22+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.1.0+4a3ec384a9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.0.1+2a5b9210a9 via fabric
	- fabric-dimensions-v1 2.1.27+72da3b3da9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.23+9ff28f40a9 via fabric
	- fabric-language-kotlin 1.8.0+kotlin.1.7.0
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.0.1+9e7660c6a9 via fabric
	- fabric-loot-tables-v1 1.1.1+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.8+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.5+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via invview
	- fabric-registry-sync-v0 0.9.16+92cf9a3ea9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.3+9e7660c6a9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- farmersdelight 1.19-0.3.0
	- fiber 0.23.0-2 via collective-fabric
	- invview 1.4.9-1.19+
	- io_leangen_geantyref_geantyref 1.3.13 via cloud
	- jankson 4.1.1+j1.2.1 via libgui
	- java 18
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- krypton 0.2.0
	- leaf-decay 1.3.1
	- ledger 1.2.5
	- libgui 6.0.0-beta.5+1.19-pre1 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- lithium 0.8.0
	- mcwdoors 1.0.6
	- mermod 1.9
	- midnightlib 0.5.2 via anthropophagy
	- minecraft 1.19
	- minimotd-fabric 2.0.8
	- mods-command 1.0.8
	- morebannerfeatures 1.1.3
	- moreorigins 1.2
	- naturescompass 1.19-2.0.4-fabric
	- net_dv8tion_jda 5.0.0-alpha.1 via disfabric
	- net_kyori_adventure-api 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-key 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-text-logger-slf4j 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-plain 4.11.0 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- net_sf_trove4j_trove4j 3.0.3 via disfabric
	- nochatreports 1.19-v1.2.3
	- notenoughcrashes 4.1.6+1.19
	- org_apache_commons_commons-collections4 4.1 via disfabric
	- org_jetbrains_annotations 16.0.1 via disfabric
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.17.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_spongepowered_configurate-core 4.1.2 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.2 via confabricate
	- org_spongepowered_configurate-gson 4.1.2 via confabricate
	- org_spongepowered_configurate-hocon 4.1.2 via confabricate
	- org_spongepowered_configurate-yaml 4.1.2 via mods-command
	- org_yaml_snakeyaml 1.31-SNAPSHOT via mods-command
	- origin-cap 1.3
	- origins 1.6.1
	- origins-classes 1.4.0
	- originsumbrellas 1.6
	- packet_tweaker 0.3.0+1.18.2 via server_translations_api
	- pehkui 3.3.2+1.14.4-1.19
	- playerabilitylib 1.6.0 via apoli
	- plushies 1.2
	- reach-entity-attributes 2.3.0 via anthropophagy
	- roughlyenoughitems 9.0.491
	- secretrooms 1.3.2+1.19
	- server_translations_api 1.4.14+1.19-rc2 via ledger
	- sgui 1.0.0-rc6+1.18-pre5 via invview
	- sihywtcamd 1.7.1+1.19
	- spark 1.9.13
	- starlight 1.1.1+fabric.ae22326
	- toms_storage 1.3.5
	- toofast 1.0.0
	- trinkets 3.4.0
	- vanish 1.4.1
	- voicechat 1.19-2.2.45
	- yigd 1.4.1-beta.1
```

**Comment by quiqueck** [comment]
Thanks for reporting. Looks like BetterEnd is not mentioned in the logs. Why do you recon this is a Bug on our end and not earthtojavamobs?
