### ISSUE TITLE
[Bug] newest BCLib abd BetterEnd not working together, gets this error

### ISSUE THREAD

**Issue by Dotismyname** [quiqueck/BetterEnd#425]
### What happened?

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Better End' (betterend) 21.0.2 with any version that is compatible with:
		 - bclib, any version
		 - bclib, any version
	 - Replace mod 'BCLib' (bclib) 3.30.1 with any version that is compatible with:
		 - minecraft 1.21
More details:
	 - Mod 'BCLib' (bclib) 3.30.1 requires version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'WunderLib' (wunderlib) 1.30.0 requires version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'Better End' (betterend) 21.0.2 requires version 21.0.5 of mod 'BCLib' (bclib), but only the wrong version is present: 3.30.1!
	 - Mod 'Better End' (betterend) 21.0.2 requires any 21.0.x version of wover, which is missing!
	 - Mod 'Better End' (betterend) 21.0.2 requires any 21.0.x version of mod 'WunderLib' (wunderlib), but only the wrong version is present: 1.30.0!
	 - Mod 'Better End' (betterend) 21.0.2 is incompatible with any version before 21.0.5 of mod 'BCLib' (bclib), but a matching version is present: 3.30.1!
	 - Mod 'Better End' (betterend) 21.0.2 is incompatible with any version before 21.0.3 of mod 'WunderLib' (wunderlib), but a matching version is present: 1.30.0!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### BetterEnd

1.21

### BCLib

1.21

### Fabric API

1.21

### Fabric Loader

1.21

### Minecraft

1.20.4

**Comment by OpenBagTwo** [comment]
As the loader says, you need version 21.0.x of BCLib (and WorldWeaver).

Note that you might want to hold off—the current version of BetterEnd is **very much** not ready for primetime (just look at the number of recent bug reports).
