### ISSUE TITLE
[Bug] tick exception 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [quiqueck/BetterEnd#473]
### What happened?

Description: Exception in server tick loop

java.lang.IllegalStateException: Biome source config is not set
	at org.betterx.betterend.world.generator.TerrainGenerator.initNoise(TerrainGenerator.java:65)
	at org.betterx.betterend.world.generator.TerrainGenerator.onServerLevelInit(TerrainGenerator.java:253)
	at MC//net.minecraft.server.world.ServerWorld.handler$bfk000$betterend$be_onServerWorldInit(ServerWorld.java:4831)
	at MC//net.minecraft.server.world.ServerWorld.<init>(ServerWorld.java:274)
	at net.minecraft.server.MinecraftServer.createWorlds(MinecraftServer.java:417)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:342)
	at MC//net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer.java:73)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:664)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583

### BetterEnd

latest 1.21.1

### BCLib

latest 1.21.1

### Fabric API

latest 1.21.1

### Fabric Loader

latest 1.21.1

### Minecraft

1.20.4

### Relevant log output

```shell
Description: Exception in server tick loop

java.lang.IllegalStateException: Biome source config is not set
	at org.betterx.betterend.world.generator.TerrainGenerator.initNoise(TerrainGenerator.java:65)
	at org.betterx.betterend.world.generator.TerrainGenerator.onServerLevelInit(TerrainGenerator.java:253)
	at MC//net.minecraft.server.world.ServerWorld.handler$bfk000$betterend$be_onServerWorldInit(ServerWorld.java:4831)
	at MC//net.minecraft.server.world.ServerWorld.<init>(ServerWorld.java:274)
	at net.minecraft.server.MinecraftServer.createWorlds(MinecraftServer.java:417)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:342)
	at MC//net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer.java:73)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:664)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583
```

**Comment by VaporeonScripts** [comment]
https://bytebin.lucko.me/Wr3Gk36vdk

**Comment by Poopooracoocoo** [comment]
#448
