### ISSUE TITLE
[Bug] Unable to read Better End guidebook item, error also appears in log [1.21.1]

### ISSUE THREAD

**Issue by Coricus** [quiqueck/BetterEnd#498]
### What happened?

I've been testing my load order, and I realized that the Better End guidebook appears to not be functioning. While it doesn't crash the game, the book certainly can't be read, either. There is also a matching error in the game logs, which I have provided in the logs section here.

This appears to be a broken integration with Patchouli from the looks of it, but the log also appears to be documenting how to fix it.

### BetterEnd

21.0.11

### BCLib

21.0.13

### Fabric API

0.107.0+1.21.1

### Fabric Loader

0.16.7-1.21.1

### Minecraft

1.20.4

### Relevant log output

```shell
[12:49:52] [Render thread/ERROR]: Failed to load book betterend:guidebook defined by mod betterend, skipping
java.lang.IllegalArgumentException: Book betterend:guidebook has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at knot/vazkii.patchouli.common.book.Book.<init>(Book.java:146) ~[Patchouli-1.21-87-FABRIC.jar:?]
	at knot/vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.21-87-FABRIC.jar:?]
	at knot/vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.21-87-FABRIC.jar:?]
	at java.base/java.util.HashMap.forEach(HashMap.java:1430) ~[?:?]
	at knot/vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.21-87-FABRIC.jar:?]
	at knot/vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:42) ~[Patchouli-1.21-87-FABRIC.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) [fabric-loader-0.16.7.jar:?]
	at knot/net.minecraft.class_310.<init>(class_310.java:477) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
```

### Other Mods

```shell
-----------------
Performance Mods
-----------------


1. Iris
2. Fabric
3. Fabric API
4. Cloth Config
5. Sodium
6. Reese's Sodium Options
7. Sodium Extra
8. Lithium
9. Indium
10. FerriteCore
11. Noisium
12. Achievements Optimizer
13. ModMenu
14. ToolTipFix
15. Krypton
16. Fabric Language Kotlin
17. Fzzy Config
18. Particle Core
19. Video Tape
20. FeyTweaks
21. Scaleable Lux
22. ImmediatelyFast
23. Extra Thicc Packets
24. ServerCore
25. Clumps
26. ModernFix


-----------------------------
Better Nether and Better End
-----------------------------

27. Architectury API
28. Roughly Enough Items

29. WorldWeaver
30. WunderLib
31. BCLib
32. BetterNether
33. BetterEnd

34. BetterEnd Crashed Ships Tweaks

35. Collective
36. Hide Experimental Warning


-----------
RPG Series
-----------

37. Player Animator
38. Better Combat

39. AzureLib Armor
40. Runes
41. Spell Engine
42. Wizards (RPG Series)
43. Archers (RPG Series)
44. Rogues and Warriors (RPG Series)
45. Paladins and Priests (RPG Series)

46. Trinkets
47. Spell Power Attributes
48. Ranged Weapon API
49. Jewelry (RPG Series)

50. Gazebos (RPG Series)


------------
YUNG's Mods
------------

51. YUNG's API

52. YUNG's Better Dungeons
53. YUNG's Better Mineshafts
54. YUNG's Better Desert Temples
55. YUNG's Better End Island
56. YUNG's Better Jungle Temples
57. YUNG's Better Nether Fortresses
58. YUNG's Better Ocean Monuments


-----------------
World Generation
-----------------

59. Tectonic
60. Geophilic

61. Dungeons and Taverns
62. SuperMartijn642corelib
63. SuperMartijn642configlib
64. Better Archaeology
65. Luki's Grand Capitals

66. Balm
67. Waystones


-----
Mobs
-----

68. Geckolib
69. Plants and Junk
70. Living Things
71. Boids 
72. Tide

73. Cat_Jam

74. Horse Armor Stand
75. Simple Netherite Horse Armor
76. Bad Horse Fix

77. MidnightLib
78. Modmenu Badges Lib
79. More Mobs

80. No Creeper Grief


----------
Villagers
----------

81. Gen's Villager Hats
82. Doors Closed
83. Village Bell Recipe
84. Nice Villagers Remastered


-------------
Macaw's Mods
-------------

85. Macaw's Windows
86. Macaw's Fences
87. Macaw's Lights
88. Macaw's Roofs
89. Macaw's Holidays


--------------------
Furniture and Decor
--------------------

90. Comforts

91. ResourcefulLib
92. Handcrafted

93. Animal Feeding Trough

94. Sooty Chimneys
95. Brick Furnace

96. Winterly

97. WATERMeDIA
98. WATERFrAMES


-----------
Sound Mods
-----------

99. Creative Core
100. Ambient Sounds
101. Sound Physics Remastered
102. Presence Footsteps
103. Auditory
104. Immersive Thunder


------------------------
Animations and Graphics
------------------------

105. Not Enough Animations
106. Eating Animation
107. Cake Chomps
108. Glore

109. Astrocraft


------
Foods
------

110. Eravern's more animal products
111. Useful Food Reborn
112. Carnival Foods
113. Caffienated

114. Despawning Eggs Hatch


----------------
Quality of Life
----------------

115. Jump Over Fences
116. FallingTree
117. Lightweight Inventory Sorting
118. Appleskin
119. Keep My Soil Tilled
120. Swing Through

121. Connectible Chains

122. Configurable
123. Yet Another Config Lib v3

124. Patchouli

125. Cherished Worlds

126. AdvancementInfo Reloaded


-------------
Enchantments
-------------

127. Cobweb
128. Soul Fire'd

129. NeoEnchant+


-----------
Ocean Mods
-----------

130. Small Ships
131. When Dungeons Arise - Seven Seas
132. Tidal Towns
133. Wakes


------------------
Ender Dragon Mods
------------------

134. True Ending
135. DragonLoot
136. Dracomlette

-----------------
Multiplayer Mods
-----------------

137. Chat Heads
138. More Chat History
139. Simple Voice Chat
140. Voice Chat Interaction


---------------
Diagnosis Mods
--------------

141. Spark


-----------
Lush Caves
-----------

142. Better Lush Caves

143. Florum Sporum


144. Better McDonalds

145. Subtle Effects
```

**Comment by vizthex123** [comment]
Same warning here. Also got one for BetterNether.

**Comment by drakray** [comment]
Came for the same thing, 21.0.11 for 1.21

**Comment by flowersnax** [comment]
same here, i can't get the guidebook to open at all 😭😭

**Comment by nanotechbl-max** [comment]
same here for b end and b nether, never knew there even was a book until i saw the error 

Book betternether:betternether_book has use_resource_pack set to false. This behaviour was removed in 1.20.

is there maybe a fix in the git for patchouli? i noticed theres a number of issue threads in the better nether git but the response to the collective issues related to this went wayyyy over my head.
