### ISSUE TITLE
[Bug] Error: "Biome source config is not set" causing crash.

### ISSUE THREAD

**Issue by crazyOC8** [quiqueck/BetterEnd#521]
### What happened?

When loading into a world in both singleplayer and a server with better end installed, the game crashes due to an error: 
"[Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Biome source config is not set"
I am unsure as what to do to fix this, and the only solution to remove the mod but I can't do that.
I expected my game to load and work normally.

### BetterEnd

21.0.11

### BCLib

21.0.13

### Fabric API

Fabric API 0.102.0+1.21

### Fabric Loader

Unknown, it's feather client fabric setting which updates daily so it should be the newest version.

### Minecraft

1.21

### Relevant log output

```shell
info: [21:09:17] [Server thread/INFO]: Added 2 Biomes
[21:09:17] [Server thread/INFO]:  - minecraft:end_midlands, subbiomes=1
[21:09:17] [Server thread/INFO]:  - minecraft:end_barrens, subbiomes=1
info: [21:09:18] [Server thread/INFO]: Added 2 Biomes
[21:09:18] [Server thread/INFO]:  - minecraft:end_midlands, subbiomes=1
[21:09:18] [Server thread/INFO]:  - minecraft:end_barrens, subbiomes=1
info: [21:09:19] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Biome source config is not set
	at knot/org.betterx.betterend.world.generator.TerrainGenerator.initNoise(TerrainGenerator.java:65) ~[better-end-21.0.11.temp.jar:?]
	at knot/org.betterx.betterend.world.generator.TerrainGenerator.onServerLevelInit(TerrainGenerator.java:253) ~[better-end-21.0.11.temp.jar:?]
	at knot/net.minecraft.class_3218.handler$zhe000$betterend$be_onServerWorldInit(class_3218.java:2831) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3218.<init>(class_3218.java:274) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:417) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:342) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1132.method_3823(class_1132.java:73) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:664) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
info: [21:09:19] [Server thread/ERROR]: This crash report has been saved to: C:\Users\cdsti_\AppData\Roaming\.minecraft\crash-reports\crash-2024-12-07_21.09.19-server.txt
info: [21:09:19] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "com.tom.cpm.shared.MinecraftServerAccess.getConfig()" because the return value of "com.tom.cpm.shared.MinecraftServerAccess.get()" is null
	at knot/com.tom.cpm.shared.config.ModConfig.getWorldConfig(ModConfig.java:13) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.temp.jar:?]
	at knot/com.tom.cpm.CustomPlayerModels.lambda$onInitialize$1(CustomPlayerModels.java:45) ~[CustomPlayerModels-Fabric-1.21-0.6.19a.temp.jar:?]
	at knot/net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.3.1+6c1df360d1-c0b4d6e7c3bfc603.jar:?]
	at knot/net.minecraft.server.MinecraftServer.handler$bjf000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:3648) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1132.method_3782(class_1132.java:228) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:735) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
info: ---- Minecraft Crash Report ----
```

### Other Mods

```shell
There are too many to list. No other mods cause this issue, everything works fine except when betterend is installed.
```

**Comment by Poopooracoocoo** [comment]
#448
