### ISSUE TITLE
[Bug] DoublePlantFeature throws IllegalArgumentException

### ISSUE THREAD

**Issue by Martmists-GH** [quiqueck/BetterEnd#523]
### What happened?

java.lang.IllegalArgumentException: Cannot set property class_2758{name=rotation, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{betterend:umbrella_moss}

### BetterEnd

4.0.11

### BCLib

3.0.14

### Fabric API

0.92.2

### Fabric Loader

1.16.9

### Minecraft

1.20.1

### Relevant log output

```shell
java.lang.IllegalArgumentException: Cannot set property class_2758{name=rotation, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{betterend:umbrella_moss}
	at knot//net.minecraft.class_2688.method_11657(class_2688.java:122)
	at knot//org.betterx.betterend.world.features.DoublePlantFeature.generate(DoublePlantFeature.java:47)
	at knot//org.betterx.betterend.world.features.DoublePlantFeature.generate(DoublePlantFeature.java:12)
	at knot//org.betterx.betterend.world.features.ScatterFeature.method_13151(ScatterFeature.java:90)
	at knot//net.minecraft.class_2975.method_12862(class_2975.java:537)
	at knot//net.minecraft.class_6796.method_39646(class_6796.java:54)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//net.minecraft.class_6796.method_39648(class_6796.java:53)
	at knot//net.minecraft.class_6796.method_39650(class_6796.java:42)
	at knot//net.minecraft.class_2794.method_12102(class_2794.java:357)
	at knot//net.minecraft.class_2806.method_51375(class_2806.java:108)
	at knot//net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at knot//net.minecraft.class_2806.md23583e$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2608)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Other Mods

```shell
- 3d\-Skin\-Layers
- AE2WTLib
- AchievementOptimizer
- Ad Astra
- Ad Astra: Giselle Addon
- Additional Lanterns
- Alloy Forgery
- Almanac
- Alternate Current
- AmbientSounds
- AppleSkin
- Applied Energistics 2
- Architectury
- Areas
- Artifacts
- Athena
- AttributeFix
- Auth Me
- AzureLib Armor
- BCLib
- Bad Wither No Cookie Reloaded
- BadOptimizations
- Balm
- Better Advancements
- Better Archeology
- Better Beds
- Better End
- Better End Delight
- Better Nether
- Better Ping Display
- Better Statistics Screen
- Better Third Person
- BetterF3
- BetterNether Delight
- BiomesOPlenty
- Block Runner
- Blockus
- Blur \(Fabric\)
- Bookshelf
- Botania
- Botarium
- BounceStyles
- Bountiful
- CC: Tweaked
- CICADA
- CTOV \- BYG Compat
- CTOV \- Friends and Foes Compat
- CTOV \- Gazebo compat
- CTOV \- Paladins & Priests compat
- CTOV \- Wizards Compat
- Cardinal Components API
- Charm of Undying
- Chat Heads
- Chipped
- ChoiceTheorem's Overhauled Village
- Chunky
- Cinderscapes
- Cloth Config v11
- Clumps
- Collective
- Concurrent Chunk Management Engine
- Continuity
- Controlling For Fabric
- Convenient mobGriefing
- CorgiLib
- CraftPresence
- Crafting Tweaks
- Crate Delight
- Crawl
- CreativeCore
- Cristel Lib
- Dark Loading Screen
- Debugify
- Diversity
- Do a Barrel Roll
- Duckling
- Dungeons and Taverns
- Dungeons and Taverns Ancient City Overhaul
- Dungeons and Taverns Pillager Outpost Rework
- Dungeons and Taverns Stronghold Rework
- Dungeons and Taverns Swamp Hut Rework
- Dungeons\+
- Echo Chest
- Elytra Slot
- EmoteTweaks
- Emotecraft
- End's Delight
- Ender Dragon Fight Remastered
- Enhanced Block Entities
- EntityCulling
- Etcetera
- Euphoria Patcher
- Explorer's Compass
- Fabric API
- Fabric Language Kotlin
- Fabric Seasons
- Fabric Seasons: Delight Compat
- Fabric Seasons: Extras
- Fabric Seasons: Terraformers Compat
- Fabric Seasons: Terralith Compat
- Falling Leaves
- FallingTree
- FancyDelight
- Farmer's Cutting: BetterNether
- Farmer's Cutting: Biomes O' Plenty
- Farmer's Cutting: Cinderscapes
- Farmer's Cutting: Oh The Biomes We've Gone
- Farmer's Cutting: Terrestria
- Farmer's Delight
- FerriteCore
- Forge Config API Port
- Formations
- Formations Nether
- Formations Overworld
- Freecam \(Modrinth Edition\)
- Friends & Foes
- Fusion
- Gamma Utils
- Gazebos
- GeckoLib 4
- Geophilic
- GlitchCore
- Global Packs
- Handcrafted
- Head In The Clouds
- Hephaestus
- Immersive Thunder
- Incendium
- Indium
- Inventory Profiles Next
- Iris
- Jade
- Jade Addons
- Jewelry \(RPG Series\)
- JumpOverFences
- Kambrik
- Katters Structures
- Krypton
- LambDynamicLights
- Lavender
- Let Me Despawn
- Litematica
- Lithium
- Lithostitched
- Lootr
- Luki's Crazy Chambers
- Luki's Grand Capitals
- MC Dungeons Armors
- MC Dungeons Weapons
- MaLiLib
- Macaw's Bridges
- Macaw's Doors
- Macaw's Fences and Walls
- Macaw's Furniture
- Macaw's Holidays
- Macaw's Lights and Lamps
- Macaw's Paintings
- Macaw's Paths and Pavings
- Macaw's Roofs
- Macaw's Stairs and Balconies
- Macaw's Trapdoors
- Macaw's Windows
- Magnum Torch
- Majrusz Library
- Majrusz's Accessories
- Malum
- Medieval Buildings
- Mod Menu
- Model Gap Fix
- More Culling
- More Delight
- More Mob Variants
- Mouse Tweaks
- Mythic Metals
- Mythic Metals Decorations
- Nature's Compass
- No Chat Reports
- Noisium
- Nullscape
- Numismatic Overhaul
- Ocean's Delight
- Oh The Biomes We've Gone
- Oh The Trees You'll Grow
- Open Parties and Claims
- Overflowing Bars
- Paladins & Priests \(RPG Series\)
- Patchouli
- Peripheralium
- Philip\`s Ruins
- Ping Wheel
- Placeholder API
- Player Animator
- Plethora
- Polymer
- Porting Lib
- Presence Footsteps
- Puzzles Lib
- Random Village Names
- RangedWeaponAPI
- Reacharound
- Rechiseled
- Reese's Sodium Options
- Replay Mod
- Resourceful Lib
- Resourcefulconfig
- Rogues & Warriors \(RPG Series\)
- Roughly Enough Items
- Runes
- Rustic Delight
- Searchables
- SeasonHUD
- Seed Delight Fabric
- Shield API
- Show Me Your Skin\!
- Shulker Box Tooltip
- Shulker Drops Two
- Simple Voice Chat
- Sodium
- Sodium Extra
- Sodium Shadowy Path Blocks
- Sound Physics Remastered
- SparseStructures
- Spell Engine
- Spell Engine x Open Parties and Claims
- Spell Power Attribute
- Spyglass Astronomy
- Starter Kit
- Status
- Stoneworks
- Storage Delight
- Structure Pool API
- Styled Nicknames
- SuperMartijn642's Config Lib
- SuperMartijn642's Core Lib
- TCD Commons API
- Tectonic
- Telepistons
- TerraBlender
- Terralith
- Terrestria
- Thigh highs etc
- Things
- Tidal Towns
- Tom's Simple Storage Mod
- ToolTip Fix
- Towns and Towers
- Trash Cans
- Traveler's Backpack
- Traverse
- Trinkets
- UniLib
- Universal Graves
- Unlimited Peripheral Works
- Vegan Delight
- Visual Workbench
- Visuality
- Waystones
- When Dungeons Arise
- Wizards \(RPG Series\)
- Xaero's Minimap
- Xaero's World Map
- YOSBR
- YUNG's API
- YetAnotherConfigLib
- Yuushya
- Zoomify
- fabric\-medievalend\-1\.0\.1
- idwtialsimmoedm
- libIPN
- lodestone\-1\.20\.1\-1\.6\.2\.3f\-fabric
- oωo
```

**Comment by paulevsGitch** [comment]
This is c2me incompatibility, disable c2me's threaded feature in its config
